/**
 * FidelityPay Merchant SDK API
 * Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FidelitypaySdk);
  }
}(this, function(expect, FidelitypaySdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FidelitypaySdk.MerchantPaymentRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MerchantPaymentRequest', function() {
    it('should create an instance of MerchantPaymentRequest', function() {
      // uncomment below and update the code to test MerchantPaymentRequest
      //var instance = new FidelitypaySdk.MerchantPaymentRequest();
      //expect(instance).to.be.a(FidelitypaySdk.MerchantPaymentRequest);
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new FidelitypaySdk.MerchantPaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new FidelitypaySdk.MerchantPaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instance = new FidelitypaySdk.MerchantPaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property operator (base name: "operator")', function() {
      // uncomment below and update the code to test the property operator
      //var instance = new FidelitypaySdk.MerchantPaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property customer (base name: "customer")', function() {
      // uncomment below and update the code to test the property customer
      //var instance = new FidelitypaySdk.MerchantPaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property returnUrl (base name: "returnUrl")', function() {
      // uncomment below and update the code to test the property returnUrl
      //var instance = new FidelitypaySdk.MerchantPaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property cancelUrl (base name: "cancelUrl")', function() {
      // uncomment below and update the code to test the property cancelUrl
      //var instance = new FidelitypaySdk.MerchantPaymentRequest();
      //expect(instance).to.be();
    });

  });

}));
