/**
 * FidelityPay Merchant SDK API
 * Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FidelitypaySdk);
  }
}(this, function(expect, FidelitypaySdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FidelitypaySdk.MerchantPaymentResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MerchantPaymentResponse', function() {
    it('should create an instance of MerchantPaymentResponse', function() {
      // uncomment below and update the code to test MerchantPaymentResponse
      //var instance = new FidelitypaySdk.MerchantPaymentResponse();
      //expect(instance).to.be.a(FidelitypaySdk.MerchantPaymentResponse);
    });

    it('should have the property paymentId (base name: "paymentId")', function() {
      // uncomment below and update the code to test the property paymentId
      //var instance = new FidelitypaySdk.MerchantPaymentResponse();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new FidelitypaySdk.MerchantPaymentResponse();
      //expect(instance).to.be();
    });

    it('should have the property paymentUrl (base name: "paymentUrl")', function() {
      // uncomment below and update the code to test the property paymentUrl
      //var instance = new FidelitypaySdk.MerchantPaymentResponse();
      //expect(instance).to.be();
    });

    it('should have the property provider (base name: "provider")', function() {
      // uncomment below and update the code to test the property provider
      //var instance = new FidelitypaySdk.MerchantPaymentResponse();
      //expect(instance).to.be();
    });

    it('should have the property flowType (base name: "flowType")', function() {
      // uncomment below and update the code to test the property flowType
      //var instance = new FidelitypaySdk.MerchantPaymentResponse();
      //expect(instance).to.be();
    });

    it('should have the property operator (base name: "operator")', function() {
      // uncomment below and update the code to test the property operator
      //var instance = new FidelitypaySdk.MerchantPaymentResponse();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instance = new FidelitypaySdk.MerchantPaymentResponse();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new FidelitypaySdk.MerchantPaymentResponse();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new FidelitypaySdk.MerchantPaymentResponse();
      //expect(instance).to.be();
    });

    it('should have the property nextAction (base name: "nextAction")', function() {
      // uncomment below and update the code to test the property nextAction
      //var instance = new FidelitypaySdk.MerchantPaymentResponse();
      //expect(instance).to.be();
    });

    it('should have the property failureReason (base name: "failureReason")', function() {
      // uncomment below and update the code to test the property failureReason
      //var instance = new FidelitypaySdk.MerchantPaymentResponse();
      //expect(instance).to.be();
    });

    it('should have the property errorType (base name: "errorType")', function() {
      // uncomment below and update the code to test the property errorType
      //var instance = new FidelitypaySdk.MerchantPaymentResponse();
      //expect(instance).to.be();
    });

    it('should have the property failureStage (base name: "failureStage")', function() {
      // uncomment below and update the code to test the property failureStage
      //var instance = new FidelitypaySdk.MerchantPaymentResponse();
      //expect(instance).to.be();
    });

  });

}));
