/**
 * FidelityPay Merchant SDK API
 * Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FidelitypaySdk);
  }
}(this, function(expect, FidelitypaySdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FidelitypaySdk.OtpActionRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OtpActionRequest', function() {
    it('should create an instance of OtpActionRequest', function() {
      // uncomment below and update the code to test OtpActionRequest
      //var instance = new FidelitypaySdk.OtpActionRequest();
      //expect(instance).to.be.a(FidelitypaySdk.OtpActionRequest);
    });

    it('should have the property otp (base name: "otp")', function() {
      // uncomment below and update the code to test the property otp
      //var instance = new FidelitypaySdk.OtpActionRequest();
      //expect(instance).to.be();
    });

  });

}));
