/*
 * FidelityPay Merchant SDK API
 *
 * Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using fidelitypay_sdk.Model;
using fidelitypay_sdk.Client;
using System.Reflection;

namespace fidelitypay_sdk.Test.Model
{
    /// <summary>
    ///  Class for testing MerchantPaymentRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MerchantPaymentRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MerchantPaymentRequest
        //private MerchantPaymentRequest instance;

        public MerchantPaymentRequestTests()
        {
            // TODO uncomment below to create an instance of MerchantPaymentRequest
            //instance = new MerchantPaymentRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MerchantPaymentRequest
        /// </summary>
        [Fact]
        public void MerchantPaymentRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" MerchantPaymentRequest
            //Assert.IsType<MerchantPaymentRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

        /// <summary>
        /// Test the property 'Operator'
        /// </summary>
        [Fact]
        public void OperatorTest()
        {
            // TODO unit test for the property 'Operator'
        }

        /// <summary>
        /// Test the property 'Customer'
        /// </summary>
        [Fact]
        public void CustomerTest()
        {
            // TODO unit test for the property 'Customer'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'ReturnUrl'
        /// </summary>
        [Fact]
        public void ReturnUrlTest()
        {
            // TODO unit test for the property 'ReturnUrl'
        }

        /// <summary>
        /// Test the property 'CancelUrl'
        /// </summary>
        [Fact]
        public void CancelUrlTest()
        {
            // TODO unit test for the property 'CancelUrl'
        }
    }
}
