/*
 * FidelityPay Merchant SDK API
 *
 * Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using fidelitypay_sdk.Model;
using fidelitypay_sdk.Client;
using System.Reflection;

namespace fidelitypay_sdk.Test.Model
{
    /// <summary>
    ///  Class for testing MerchantPaymentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MerchantPaymentResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MerchantPaymentResponse
        //private MerchantPaymentResponse instance;

        public MerchantPaymentResponseTests()
        {
            // TODO uncomment below to create an instance of MerchantPaymentResponse
            //instance = new MerchantPaymentResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MerchantPaymentResponse
        /// </summary>
        [Fact]
        public void MerchantPaymentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" MerchantPaymentResponse
            //Assert.IsType<MerchantPaymentResponse>(instance);
        }

        /// <summary>
        /// Test the property 'PaymentId'
        /// </summary>
        [Fact]
        public void PaymentIdTest()
        {
            // TODO unit test for the property 'PaymentId'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'PaymentUrl'
        /// </summary>
        [Fact]
        public void PaymentUrlTest()
        {
            // TODO unit test for the property 'PaymentUrl'
        }

        /// <summary>
        /// Test the property 'Provider'
        /// </summary>
        [Fact]
        public void ProviderTest()
        {
            // TODO unit test for the property 'Provider'
        }

        /// <summary>
        /// Test the property 'FlowType'
        /// </summary>
        [Fact]
        public void FlowTypeTest()
        {
            // TODO unit test for the property 'FlowType'
        }

        /// <summary>
        /// Test the property 'Operator'
        /// </summary>
        [Fact]
        public void OperatorTest()
        {
            // TODO unit test for the property 'Operator'
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'NextAction'
        /// </summary>
        [Fact]
        public void NextActionTest()
        {
            // TODO unit test for the property 'NextAction'
        }

        /// <summary>
        /// Test the property 'FailureReason'
        /// </summary>
        [Fact]
        public void FailureReasonTest()
        {
            // TODO unit test for the property 'FailureReason'
        }

        /// <summary>
        /// Test the property 'ErrorType'
        /// </summary>
        [Fact]
        public void ErrorTypeTest()
        {
            // TODO unit test for the property 'ErrorType'
        }

        /// <summary>
        /// Test the property 'FailureStage'
        /// </summary>
        [Fact]
        public void FailureStageTest()
        {
            // TODO unit test for the property 'FailureStage'
        }
    }
}
