/*
 * FidelityPay Merchant SDK API
 *
 * Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using fidelitypay_sdk.Model;
using fidelitypay_sdk.Client;
using System.Reflection;

namespace fidelitypay_sdk.Test.Model
{
    /// <summary>
    ///  Class for testing NextAction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NextActionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NextAction
        //private NextAction instance;

        public NextActionTests()
        {
            // TODO uncomment below to create an instance of NextAction
            //instance = new NextAction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NextAction
        /// </summary>
        [Fact]
        public void NextActionInstanceTest()
        {
            // TODO uncomment below to test "IsType" NextAction
            //Assert.IsType<NextAction>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Provider'
        /// </summary>
        [Fact]
        public void ProviderTest()
        {
            // TODO unit test for the property 'Provider'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
