/*
 * FidelityPay Merchant SDK API
 *
 * Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using fidelitypay_sdk.Model;
using fidelitypay_sdk.Client;
using System.Reflection;

namespace fidelitypay_sdk.Test.Model
{
    /// <summary>
    ///  Class for testing OtpActionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OtpActionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OtpActionRequest
        //private OtpActionRequest instance;

        public OtpActionRequestTests()
        {
            // TODO uncomment below to create an instance of OtpActionRequest
            //instance = new OtpActionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OtpActionRequest
        /// </summary>
        [Fact]
        public void OtpActionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OtpActionRequest
            //Assert.IsType<OtpActionRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Otp'
        /// </summary>
        [Fact]
        public void OtpTest()
        {
            // TODO unit test for the property 'Otp'
        }
    }
}
