# coding: utf-8

"""
    FidelityPay Merchant SDK API

    Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fidelitypay_sdk.models.otp_action_request import OtpActionRequest

class TestOtpActionRequest(unittest.TestCase):
    """OtpActionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OtpActionRequest:
        """Test OtpActionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OtpActionRequest`
        """
        model = OtpActionRequest()
        if include_optional:
            return OtpActionRequest(
                otp = '012'
            )
        else:
            return OtpActionRequest(
                otp = '012',
        )
        """

    def testOtpActionRequest(self):
        """Test OtpActionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
