# coding: utf-8

"""
    FidelityPay Merchant SDK API

    Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fidelitypay_sdk.models.merchant_payment_request import MerchantPaymentRequest

class TestMerchantPaymentRequest(unittest.TestCase):
    """MerchantPaymentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantPaymentRequest:
        """Test MerchantPaymentRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantPaymentRequest`
        """
        model = MerchantPaymentRequest()
        if include_optional:
            return MerchantPaymentRequest(
                amount = 1,
                currency = 'XOF',
                country = '01',
                operator = '',
                customer = fidelitypay_sdk.models.customer.Customer(
                    phone = '', 
                    firstname = '', 
                    lastname = '', 
                    email = '', ),
                return_url = '',
                cancel_url = ''
            )
        else:
            return MerchantPaymentRequest(
                currency = 'XOF',
                country = '01',
                operator = '',
                customer = fidelitypay_sdk.models.customer.Customer(
                    phone = '', 
                    firstname = '', 
                    lastname = '', 
                    email = '', ),
        )
        """

    def testMerchantPaymentRequest(self):
        """Test MerchantPaymentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
