# coding: utf-8

"""
    FidelityPay Merchant SDK API

    Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fidelitypay_sdk.api.merchant_pay_in_api import MerchantPayInApi


class TestMerchantPayInApi(unittest.TestCase):
    """MerchantPayInApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MerchantPayInApi()

    def tearDown(self) -> None:
        pass

    def test_get_payment(self) -> None:
        """Test case for get_payment

        Read a merchant pay-in
        """
        pass

    def test_initiate(self) -> None:
        """Test case for initiate

        Initiate a merchant pay-in
        """
        pass

    def test_submit_otp(self) -> None:
        """Test case for submit_otp

        Submit a required OTP action
        """
        pass


if __name__ == '__main__':
    unittest.main()
