# coding: utf-8

"""
    FidelityPay Merchant SDK API

    Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fidelitypay_sdk.models.next_action import NextAction

class TestNextAction(unittest.TestCase):
    """NextAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NextAction:
        """Test NextAction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NextAction`
        """
        model = NextAction()
        if include_optional:
            return NextAction(
                type = '',
                provider = '',
                message = ''
            )
        else:
            return NextAction(
        )
        """

    def testNextAction(self):
        """Test NextAction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
