/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package fidelitypay_sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import fidelitypay_sdk.models.MerchantPaymentResponse
import fidelitypay_sdk.models.NextAction

class MerchantPaymentResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MerchantPaymentResponse
        //val modelInstance = MerchantPaymentResponse()

        // to test the property `paymentId`
        should("test paymentId") {
            // uncomment below to test the property
            //modelInstance.paymentId shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `paymentUrl`
        should("test paymentUrl") {
            // uncomment below to test the property
            //modelInstance.paymentUrl shouldBe ("TODO")
        }

        // to test the property `provider`
        should("test provider") {
            // uncomment below to test the property
            //modelInstance.provider shouldBe ("TODO")
        }

        // to test the property `flowType`
        should("test flowType") {
            // uncomment below to test the property
            //modelInstance.flowType shouldBe ("TODO")
        }

        // to test the property ``operator``
        should("test `operator`") {
            // uncomment below to test the property
            //modelInstance.`operator` shouldBe ("TODO")
        }

        // to test the property `country`
        should("test country") {
            // uncomment below to test the property
            //modelInstance.country shouldBe ("TODO")
        }

        // to test the property `amount`
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `currency`
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `nextAction`
        should("test nextAction") {
            // uncomment below to test the property
            //modelInstance.nextAction shouldBe ("TODO")
        }

        // to test the property `failureReason`
        should("test failureReason") {
            // uncomment below to test the property
            //modelInstance.failureReason shouldBe ("TODO")
        }

        // to test the property `errorType`
        should("test errorType") {
            // uncomment below to test the property
            //modelInstance.errorType shouldBe ("TODO")
        }

        // to test the property `failureStage`
        should("test failureStage") {
            // uncomment below to test the property
            //modelInstance.failureStage shouldBe ("TODO")
        }

    }
}
