/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package fidelitypay_sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import fidelitypay_sdk.models.OtpActionRequest

class OtpActionRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OtpActionRequest
        //val modelInstance = OtpActionRequest()

        // to test the property `otp`
        should("test otp") {
            // uncomment below to test the property
            //modelInstance.otp shouldBe ("TODO")
        }

    }
}
