package com.Api.Fidelitypay.enums;

/**
 * Codes métier normalisés pour les échecs de paiement (v1 pragmatique).
 * Les cas non reconnus doivent utiliser {@link #UNKNOWN}.
 */
public enum FailureReason {
  UNKNOWN,
  INVALID_PHONE_NUMBER,
  NO_PROVIDER_AVAILABLE_FOR_COUNTRY,
  NO_PROVIDER_AVAILABLE_FOR_ENVIRONMENT,
  UNSUPPORTED_PAYIN_CAPABILITY,
  NO_FALLBACK_PROVIDER_AVAILABLE,
  AUTHENTICATION_FAILED,
  TIMEOUT,
  NETWORK_ERROR,
  PROVIDER_DOWN,
  BAD_REQUEST,
  INTERNAL_ERROR,
  INSUFFICIENT_FUNDS,
  INVALID_OPERATOR,
  CANCELLED_BY_USER,
  PROVIDER_REPORTED_FAILURE,
  PROVIDER_RESULT_UNKNOWN,
  OTP_VALIDATION_FAILED,
  LIMIT_EXCEEDED,
  CUSTOMER_NOT_REACHABLE,
  PAYMENT_ABANDONED,
  PAYMENT_EXPIRED,
  CARD_DECLINED,
  CARD_EXPIRED,
  INVALID_CARD_DETAILS,
  PENDING_TOO_LONG,
  PROVIDER_CONFIGURATION_ERROR,
  CURRENCY_NOT_SUPPORTED,
  DUPLICATE_TRANSACTION
}
