/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package fidelitypay_sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param firstname 
 * @param lastname 
 * @param phone 
 * @param email 
 */


data class Customer (

    @Json(name = "firstname")
    val firstname: kotlin.String,

    @Json(name = "lastname")
    val lastname: kotlin.String,

    @Json(name = "phone")
    val phone: kotlin.String? = null,

    @Json(name = "email")
    val email: kotlin.String? = null

) {


}

