/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package fidelitypay_sdk.models

import fidelitypay_sdk.models.Customer

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param currency 
 * @param country 
 * @param `operator` 
 * @param customer 
 * @param amount 
 * @param returnUrl 
 * @param cancelUrl 
 */


data class MerchantPaymentRequest (

    @Json(name = "currency")
    val currency: kotlin.String,

    @Json(name = "country")
    val country: kotlin.String,

    @Json(name = "operator")
    val `operator`: kotlin.String,

    @Json(name = "customer")
    val customer: Customer,

    @Json(name = "amount")
    val amount: kotlin.Long? = null,

    @Json(name = "returnUrl")
    val returnUrl: kotlin.String? = null,

    @Json(name = "cancelUrl")
    val cancelUrl: kotlin.String? = null

) {


}

