/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package fidelitypay_sdk.models

import fidelitypay_sdk.models.NextAction

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param paymentId 
 * @param status 
 * @param paymentUrl 
 * @param provider 
 * @param flowType 
 * @param `operator` 
 * @param country 
 * @param amount 
 * @param currency 
 * @param nextAction 
 * @param failureReason 
 * @param errorType 
 * @param failureStage 
 */


data class MerchantPaymentResponse (

    @Json(name = "paymentId")
    val paymentId: kotlin.String? = null,

    @Json(name = "status")
    val status: MerchantPaymentResponse.Status? = null,

    @Json(name = "paymentUrl")
    val paymentUrl: kotlin.String? = null,

    @Json(name = "provider")
    val provider: kotlin.String? = null,

    @Json(name = "flowType")
    val flowType: kotlin.String? = null,

    @Json(name = "operator")
    val `operator`: kotlin.String? = null,

    @Json(name = "country")
    val country: kotlin.String? = null,

    @Json(name = "amount")
    val amount: java.math.BigDecimal? = null,

    @Json(name = "currency")
    val currency: kotlin.String? = null,

    @Json(name = "nextAction")
    val nextAction: NextAction? = null,

    @Json(name = "failureReason")
    val failureReason: kotlin.String? = null,

    @Json(name = "errorType")
    val errorType: MerchantPaymentResponse.ErrorType? = null,

    @Json(name = "failureStage")
    val failureStage: MerchantPaymentResponse.FailureStage? = null

) {

    /**
     * 
     *
     * Values: PENDING,REQUIRES_ACTION,PENDING_RECONCILIATION,SUCCESS,FAILED,CANCELLED
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "PENDING") PENDING("PENDING"),
        @Json(name = "REQUIRES_ACTION") REQUIRES_ACTION("REQUIRES_ACTION"),
        @Json(name = "PENDING_RECONCILIATION") PENDING_RECONCILIATION("PENDING_RECONCILIATION"),
        @Json(name = "SUCCESS") SUCCESS("SUCCESS"),
        @Json(name = "FAILED") FAILED("FAILED"),
        @Json(name = "CANCELLED") CANCELLED("CANCELLED");
    }
    /**
     * 
     *
     * Values: NETWORK,TIMEOUT,AUTHENTICATION,PROVIDER_DOWN,BAD_REQUEST,INTERNAL_ERROR,UNKNOWN
     */
    @JsonClass(generateAdapter = false)
    enum class ErrorType(val value: kotlin.String) {
        @Json(name = "NETWORK") NETWORK("NETWORK"),
        @Json(name = "TIMEOUT") TIMEOUT("TIMEOUT"),
        @Json(name = "AUTHENTICATION") AUTHENTICATION("AUTHENTICATION"),
        @Json(name = "PROVIDER_DOWN") PROVIDER_DOWN("PROVIDER_DOWN"),
        @Json(name = "BAD_REQUEST") BAD_REQUEST("BAD_REQUEST"),
        @Json(name = "INTERNAL_ERROR") INTERNAL_ERROR("INTERNAL_ERROR"),
        @Json(name = "UNKNOWN") UNKNOWN("UNKNOWN");
    }
    /**
     * 
     *
     * Values: VALIDATION,ROUTING,PROVIDER_INIT,PROVIDER_ACTION,PROVIDER_CALLBACK,RECONCILIATION,INTERNAL,UNKNOWN
     */
    @JsonClass(generateAdapter = false)
    enum class FailureStage(val value: kotlin.String) {
        @Json(name = "VALIDATION") VALIDATION("VALIDATION"),
        @Json(name = "ROUTING") ROUTING("ROUTING"),
        @Json(name = "PROVIDER_INIT") PROVIDER_INIT("PROVIDER_INIT"),
        @Json(name = "PROVIDER_ACTION") PROVIDER_ACTION("PROVIDER_ACTION"),
        @Json(name = "PROVIDER_CALLBACK") PROVIDER_CALLBACK("PROVIDER_CALLBACK"),
        @Json(name = "RECONCILIATION") RECONCILIATION("RECONCILIATION"),
        @Json(name = "INTERNAL") INTERNAL("INTERNAL"),
        @Json(name = "UNKNOWN") UNKNOWN("UNKNOWN");
    }

}

