spring.application.name=Fidelitypay
# DB Config
spring.datasource.url=jdbc:mysql://localhost:3306/fidelityapi?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
# Force l'exécution de data.sql à chaque démarrage
spring.sql.init.mode=always
# Attend que Hibernate ait fini de créer les tables avant d'insérer les donnée
# Actuator pour monitoring
management.endpoints.web.exposure.include=health,info

# PayDunya Configuration
# PayDunya Configuration
paydunya.api.base-url=https://app.paydunya.com/api/v1
paydunya.api.master-key=test_public_D8WC4iRUOknbiBADdTXKLHVmZxq
paydunya.api.private-key=test_private_R9RNxIfu9nEPprWQJtqmeD3nPtw
paydunya.api.token=s4zUxsEeuwF7LUMUAlCF
paydunya.store.name=FidelityPay Store

# KkiaPay Configuration
kkiapay.api.base-url=https://api.kkiapay.me
kkiapay.api.public-key=f93862db9d083a3f670cc7c03b8a86b4ae37ee45
kkiapay.api.private-key=pk_9f6c5c776ed7765f29f1d5aaa0dbeeb30f2ba1f7472e538292b35f9d60b75ee5
kkiapay.api.token=test_token
kkiapay.store.name=FidelityPay Store

# HTTP client timeouts (ms)
http.connect.timeout=3000
http.read.timeout=5000