/*
 * FidelityPay Merchant SDK API
 *
 * Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using fidelitypay_sdk.Api;
using fidelitypay_sdk.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace fidelitypay_sdk.Test.Api
{
    /// <summary>
    ///  Class for testing MerchantPayInApi
    /// </summary>
    public sealed class MerchantPayInApiTests : ApiTestsBase
    {
        private readonly IMerchantPayInApi _instance;

        public MerchantPayInApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IMerchantPayInApi>();
        }

        /// <summary>
        /// Test GetPayment
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetPaymentAsyncTest()
        {
            string xAPIKey = default!;
            string paymentId = default!;
            var response = await _instance.GetPaymentAsync(xAPIKey, paymentId);
            var model = response.Ok();
            Assert.IsType<MerchantPaymentResponse>(model);
        }

        /// <summary>
        /// Test Initiate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task InitiateAsyncTest()
        {
            string xAPIKey = default!;
            string idempotencyKey = default!;
            MerchantPaymentRequest merchantPaymentRequest = default!;
            var response = await _instance.InitiateAsync(xAPIKey, idempotencyKey, merchantPaymentRequest);
            var model = response.Ok();
            Assert.IsType<MerchantPaymentResponse>(model);
        }

        /// <summary>
        /// Test SubmitOtp
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task SubmitOtpAsyncTest()
        {
            string xAPIKey = default!;
            string paymentId = default!;
            OtpActionRequest otpActionRequest = default!;
            var response = await _instance.SubmitOtpAsync(xAPIKey, paymentId, otpActionRequest);
            var model = response.Ok();
            Assert.IsType<MerchantPaymentResponse>(model);
        }
    }
}
