/**
 * FidelityPay Merchant SDK API
 * Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Customer from './model/Customer';
import MerchantPaymentRequest from './model/MerchantPaymentRequest';
import MerchantPaymentResponse from './model/MerchantPaymentResponse';
import NextAction from './model/NextAction';
import OtpActionRequest from './model/OtpActionRequest';
import MerchantPayInApi from './api/MerchantPayInApi';


/**
* Public endpoints for third-party merchant integrations. Authenticate every request with the &#x60;X-API-Key&#x60; header. .<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var FidelitypaySdk = require('index'); // See note below*.
* var xxxSvc = new FidelitypaySdk.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new FidelitypaySdk.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new FidelitypaySdk.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new FidelitypaySdk.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Customer model constructor.
     * @property {module:model/Customer}
     */
    Customer,

    /**
     * The MerchantPaymentRequest model constructor.
     * @property {module:model/MerchantPaymentRequest}
     */
    MerchantPaymentRequest,

    /**
     * The MerchantPaymentResponse model constructor.
     * @property {module:model/MerchantPaymentResponse}
     */
    MerchantPaymentResponse,

    /**
     * The NextAction model constructor.
     * @property {module:model/NextAction}
     */
    NextAction,

    /**
     * The OtpActionRequest model constructor.
     * @property {module:model/OtpActionRequest}
     */
    OtpActionRequest,

    /**
    * The MerchantPayInApi service constructor.
    * @property {module:api/MerchantPayInApi}
    */
    MerchantPayInApi
};
