/* tslint:disable */
/* eslint-disable */
/**
 * FidelityPay Merchant SDK API
 * Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface Customer {
    'phone'?: string;
    'firstname': string;
    'lastname': string;
    'email'?: string;
}
export interface MerchantPaymentRequest {
    'amount'?: number;
    'currency': string;
    'country': string;
    'operator': string;
    'customer': Customer;
    'returnUrl'?: string;
    'cancelUrl'?: string;
}
export interface MerchantPaymentResponse {
    'paymentId'?: string;
    'status'?: MerchantPaymentResponseStatusEnum;
    'paymentUrl'?: string;
    'provider'?: string;
    'flowType'?: string;
    'operator'?: string;
    'country'?: string;
    'amount'?: number;
    'currency'?: string;
    'nextAction'?: NextAction;
    'failureReason'?: string;
    'errorType'?: MerchantPaymentResponseErrorTypeEnum;
    'failureStage'?: MerchantPaymentResponseFailureStageEnum;
}

export const MerchantPaymentResponseStatusEnum = {
    Pending: 'PENDING',
    RequiresAction: 'REQUIRES_ACTION',
    PendingReconciliation: 'PENDING_RECONCILIATION',
    Success: 'SUCCESS',
    Failed: 'FAILED',
    Cancelled: 'CANCELLED',
} as const;

export type MerchantPaymentResponseStatusEnum = typeof MerchantPaymentResponseStatusEnum[keyof typeof MerchantPaymentResponseStatusEnum];
export const MerchantPaymentResponseErrorTypeEnum = {
    Network: 'NETWORK',
    Timeout: 'TIMEOUT',
    Authentication: 'AUTHENTICATION',
    ProviderDown: 'PROVIDER_DOWN',
    BadRequest: 'BAD_REQUEST',
    InternalError: 'INTERNAL_ERROR',
    Unknown: 'UNKNOWN',
} as const;

export type MerchantPaymentResponseErrorTypeEnum = typeof MerchantPaymentResponseErrorTypeEnum[keyof typeof MerchantPaymentResponseErrorTypeEnum];
export const MerchantPaymentResponseFailureStageEnum = {
    Validation: 'VALIDATION',
    Routing: 'ROUTING',
    ProviderInit: 'PROVIDER_INIT',
    ProviderAction: 'PROVIDER_ACTION',
    ProviderCallback: 'PROVIDER_CALLBACK',
    Reconciliation: 'RECONCILIATION',
    Internal: 'INTERNAL',
    Unknown: 'UNKNOWN',
} as const;

export type MerchantPaymentResponseFailureStageEnum = typeof MerchantPaymentResponseFailureStageEnum[keyof typeof MerchantPaymentResponseFailureStageEnum];

export interface NextAction {
    'type'?: string;
    'provider'?: string;
    'message'?: string;
}
export interface OtpActionRequest {
    'otp': string;
}

/**
 * MerchantPayInApi - axios parameter creator
 */
export const MerchantPayInApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Read a merchant pay-in
         * @param {string} xAPIKey 
         * @param {string} paymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPayment: async (xAPIKey: string, paymentId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xAPIKey' is not null or undefined
            assertParamExists('getPayment', 'xAPIKey', xAPIKey)
            // verify required parameter 'paymentId' is not null or undefined
            assertParamExists('getPayment', 'paymentId', paymentId)
            const localVarPath = `/api/v1/payments/{paymentId}`
                .replace('{paymentId}', encodeURIComponent(String(paymentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Public API endpoint for merchant servers and SDKs. Uses X-API-Key and Idempotency-Key headers.
         * @summary Initiate a merchant pay-in
         * @param {string} xAPIKey 
         * @param {string} idempotencyKey 
         * @param {MerchantPaymentRequest} merchantPaymentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        initiate: async (xAPIKey: string, idempotencyKey: string, merchantPaymentRequest: MerchantPaymentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xAPIKey' is not null or undefined
            assertParamExists('initiate', 'xAPIKey', xAPIKey)
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('initiate', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'merchantPaymentRequest' is not null or undefined
            assertParamExists('initiate', 'merchantPaymentRequest', merchantPaymentRequest)
            const localVarPath = `/api/v1/payments/initiate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(merchantPaymentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Submit a required OTP action
         * @param {string} xAPIKey 
         * @param {string} paymentId 
         * @param {OtpActionRequest} otpActionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitOtp: async (xAPIKey: string, paymentId: string, otpActionRequest: OtpActionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xAPIKey' is not null or undefined
            assertParamExists('submitOtp', 'xAPIKey', xAPIKey)
            // verify required parameter 'paymentId' is not null or undefined
            assertParamExists('submitOtp', 'paymentId', paymentId)
            // verify required parameter 'otpActionRequest' is not null or undefined
            assertParamExists('submitOtp', 'otpActionRequest', otpActionRequest)
            const localVarPath = `/api/v1/payments/{paymentId}/actions/otp`
                .replace('{paymentId}', encodeURIComponent(String(paymentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(otpActionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MerchantPayInApi - functional programming interface
 */
export const MerchantPayInApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MerchantPayInApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Read a merchant pay-in
         * @param {string} xAPIKey 
         * @param {string} paymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPayment(xAPIKey: string, paymentId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MerchantPaymentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPayment(xAPIKey, paymentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MerchantPayInApi.getPayment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Public API endpoint for merchant servers and SDKs. Uses X-API-Key and Idempotency-Key headers.
         * @summary Initiate a merchant pay-in
         * @param {string} xAPIKey 
         * @param {string} idempotencyKey 
         * @param {MerchantPaymentRequest} merchantPaymentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async initiate(xAPIKey: string, idempotencyKey: string, merchantPaymentRequest: MerchantPaymentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MerchantPaymentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.initiate(xAPIKey, idempotencyKey, merchantPaymentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MerchantPayInApi.initiate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Submit a required OTP action
         * @param {string} xAPIKey 
         * @param {string} paymentId 
         * @param {OtpActionRequest} otpActionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async submitOtp(xAPIKey: string, paymentId: string, otpActionRequest: OtpActionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MerchantPaymentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.submitOtp(xAPIKey, paymentId, otpActionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MerchantPayInApi.submitOtp']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MerchantPayInApi - factory interface
 */
export const MerchantPayInApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MerchantPayInApiFp(configuration)
    return {
        /**
         * 
         * @summary Read a merchant pay-in
         * @param {string} xAPIKey 
         * @param {string} paymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPayment(xAPIKey: string, paymentId: string, options?: RawAxiosRequestConfig): AxiosPromise<MerchantPaymentResponse> {
            return localVarFp.getPayment(xAPIKey, paymentId, options).then((request) => request(axios, basePath));
        },
        /**
         * Public API endpoint for merchant servers and SDKs. Uses X-API-Key and Idempotency-Key headers.
         * @summary Initiate a merchant pay-in
         * @param {string} xAPIKey 
         * @param {string} idempotencyKey 
         * @param {MerchantPaymentRequest} merchantPaymentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        initiate(xAPIKey: string, idempotencyKey: string, merchantPaymentRequest: MerchantPaymentRequest, options?: RawAxiosRequestConfig): AxiosPromise<MerchantPaymentResponse> {
            return localVarFp.initiate(xAPIKey, idempotencyKey, merchantPaymentRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Submit a required OTP action
         * @param {string} xAPIKey 
         * @param {string} paymentId 
         * @param {OtpActionRequest} otpActionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitOtp(xAPIKey: string, paymentId: string, otpActionRequest: OtpActionRequest, options?: RawAxiosRequestConfig): AxiosPromise<MerchantPaymentResponse> {
            return localVarFp.submitOtp(xAPIKey, paymentId, otpActionRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MerchantPayInApi - object-oriented interface
 */
export class MerchantPayInApi extends BaseAPI {
    /**
     * 
     * @summary Read a merchant pay-in
     * @param {string} xAPIKey 
     * @param {string} paymentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getPayment(xAPIKey: string, paymentId: string, options?: RawAxiosRequestConfig) {
        return MerchantPayInApiFp(this.configuration).getPayment(xAPIKey, paymentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Public API endpoint for merchant servers and SDKs. Uses X-API-Key and Idempotency-Key headers.
     * @summary Initiate a merchant pay-in
     * @param {string} xAPIKey 
     * @param {string} idempotencyKey 
     * @param {MerchantPaymentRequest} merchantPaymentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public initiate(xAPIKey: string, idempotencyKey: string, merchantPaymentRequest: MerchantPaymentRequest, options?: RawAxiosRequestConfig) {
        return MerchantPayInApiFp(this.configuration).initiate(xAPIKey, idempotencyKey, merchantPaymentRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Submit a required OTP action
     * @param {string} xAPIKey 
     * @param {string} paymentId 
     * @param {OtpActionRequest} otpActionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public submitOtp(xAPIKey: string, paymentId: string, otpActionRequest: OtpActionRequest, options?: RawAxiosRequestConfig) {
        return MerchantPayInApiFp(this.configuration).submitOtp(xAPIKey, paymentId, otpActionRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



