// <auto-generated>
/*
 * FidelityPay Merchant SDK API
 *
 * Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using fidelitypay_sdk.Client;

namespace fidelitypay_sdk.Model
{
    /// <summary>
    /// Customer
    /// </summary>
    public partial class Customer : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Customer" /> class.
        /// </summary>
        /// <param name="firstname">firstname</param>
        /// <param name="lastname">lastname</param>
        /// <param name="phone">phone</param>
        /// <param name="email">email</param>
        [JsonConstructor]
        public Customer(string firstname, string lastname, Option<string?> phone = default, Option<string?> email = default)
        {
            Firstname = firstname;
            Lastname = lastname;
            PhoneOption = phone;
            EmailOption = email;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Firstname
        /// </summary>
        [JsonPropertyName("firstname")]
        public string Firstname { get; set; }

        /// <summary>
        /// Gets or Sets Lastname
        /// </summary>
        [JsonPropertyName("lastname")]
        public string Lastname { get; set; }

        /// <summary>
        /// Used to track the state of Phone
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PhoneOption { get; private set; }

        /// <summary>
        /// Gets or Sets Phone
        /// </summary>
        [JsonPropertyName("phone")]
        public string? Phone { get { return this.PhoneOption.Value; } set { this.PhoneOption = new(value); } }

        /// <summary>
        /// Used to track the state of Email
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EmailOption { get; private set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [JsonPropertyName("email")]
        public string? Email { get { return this.EmailOption.Value; } set { this.EmailOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Customer {\n");
            sb.Append("  Firstname: ").Append(Firstname).Append("\n");
            sb.Append("  Lastname: ").Append(Lastname).Append("\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Firstname (string) maxLength
            if (this.Firstname != null && this.Firstname.Length > 120)
            {
                yield return new ValidationResult("Invalid value for Firstname, length must be less than 120.", new [] { "Firstname" });
            }

            // Firstname (string) minLength
            if (this.Firstname != null && this.Firstname.Length < 0)
            {
                yield return new ValidationResult("Invalid value for Firstname, length must be greater than 0.", new [] { "Firstname" });
            }

            // Lastname (string) maxLength
            if (this.Lastname != null && this.Lastname.Length > 120)
            {
                yield return new ValidationResult("Invalid value for Lastname, length must be less than 120.", new [] { "Lastname" });
            }

            // Lastname (string) minLength
            if (this.Lastname != null && this.Lastname.Length < 0)
            {
                yield return new ValidationResult("Invalid value for Lastname, length must be greater than 0.", new [] { "Lastname" });
            }

            // Phone (string) maxLength
            if (this.Phone != null && this.Phone.Length > 50)
            {
                yield return new ValidationResult("Invalid value for Phone, length must be less than 50.", new [] { "Phone" });
            }

            // Phone (string) minLength
            if (this.Phone != null && this.Phone.Length < 0)
            {
                yield return new ValidationResult("Invalid value for Phone, length must be greater than 0.", new [] { "Phone" });
            }

            // Email (string) maxLength
            if (this.Email != null && this.Email.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Email, length must be less than 255.", new [] { "Email" });
            }

            // Email (string) minLength
            if (this.Email != null && this.Email.Length < 0)
            {
                yield return new ValidationResult("Invalid value for Email, length must be greater than 0.", new [] { "Email" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Customer" />
    /// </summary>
    public partial class CustomerJsonConverter : JsonConverter<Customer>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="CustomerJsonConverter" /> class.
        /// </summary>
        public CustomerJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="Customer" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Customer Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> firstname = default;
            Option<string?> lastname = default;
            Option<string?> phone = default;
            Option<string?> email = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "firstname":
                            firstname = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "lastname":
                            lastname = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "phone":
                            phone = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "email":
                            email = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!firstname.IsSet)
                throw new ArgumentException("Property is required for class Customer.", nameof(firstname));

            if (!lastname.IsSet)
                throw new ArgumentException("Property is required for class Customer.", nameof(lastname));

            if (firstname.IsSet && firstname.Value == null)
                throw new ArgumentNullException(nameof(firstname), "Property is not nullable for class Customer.");

            if (lastname.IsSet && lastname.Value == null)
                throw new ArgumentNullException(nameof(lastname), "Property is not nullable for class Customer.");

            if (phone.IsSet && phone.Value == null)
                throw new ArgumentNullException(nameof(phone), "Property is not nullable for class Customer.");

            if (email.IsSet && email.Value == null)
                throw new ArgumentNullException(nameof(email), "Property is not nullable for class Customer.");

            return new Customer(firstname.Value!, lastname.Value!, phone, email);
        }

        /// <summary>
        /// Serializes a <see cref="Customer" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="customer"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Customer customer, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, customer, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Customer" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="customer"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Customer customer, JsonSerializerOptions jsonSerializerOptions)
        {
            if (customer.Firstname == null)
                throw new ArgumentNullException(nameof(customer.Firstname), "Property is required for class Customer.");

            if (customer.Lastname == null)
                throw new ArgumentNullException(nameof(customer.Lastname), "Property is required for class Customer.");

            if (customer.PhoneOption.IsSet && customer.Phone == null)
                throw new ArgumentNullException(nameof(customer.Phone), "Property is required for class Customer.");

            if (customer.EmailOption.IsSet && customer.Email == null)
                throw new ArgumentNullException(nameof(customer.Email), "Property is required for class Customer.");

            writer.WriteString("firstname", customer.Firstname);

            writer.WriteString("lastname", customer.Lastname);

            if (customer.PhoneOption.IsSet)
                writer.WriteString("phone", customer.Phone);

            if (customer.EmailOption.IsSet)
                writer.WriteString("email", customer.Email);
        }
    }
}
