// <auto-generated>
/*
 * FidelityPay Merchant SDK API
 *
 * Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using fidelitypay_sdk.Client;

namespace fidelitypay_sdk.Model
{
    /// <summary>
    /// MerchantPaymentResponse
    /// </summary>
    public partial class MerchantPaymentResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MerchantPaymentResponse" /> class.
        /// </summary>
        /// <param name="paymentId">paymentId</param>
        /// <param name="status">status</param>
        /// <param name="paymentUrl">paymentUrl</param>
        /// <param name="provider">provider</param>
        /// <param name="flowType">flowType</param>
        /// <param name="operator">operator</param>
        /// <param name="country">country</param>
        /// <param name="amount">amount</param>
        /// <param name="currency">currency</param>
        /// <param name="nextAction">nextAction</param>
        /// <param name="failureReason">failureReason</param>
        /// <param name="errorType">errorType</param>
        /// <param name="failureStage">failureStage</param>
        [JsonConstructor]
        public MerchantPaymentResponse(Option<string?> paymentId = default, Option<StatusEnum?> status = default, Option<string?> paymentUrl = default, Option<string?> provider = default, Option<string?> flowType = default, Option<string?> @operator = default, Option<string?> country = default, Option<decimal?> amount = default, Option<string?> currency = default, Option<NextAction?> nextAction = default, Option<string?> failureReason = default, Option<ErrorTypeEnum?> errorType = default, Option<FailureStageEnum?> failureStage = default)
        {
            PaymentIdOption = paymentId;
            StatusOption = status;
            PaymentUrlOption = paymentUrl;
            ProviderOption = provider;
            FlowTypeOption = flowType;
            OperatorOption = @operator;
            CountryOption = country;
            AmountOption = amount;
            CurrencyOption = currency;
            NextActionOption = nextAction;
            FailureReasonOption = failureReason;
            ErrorTypeOption = errorType;
            FailureStageOption = failureStage;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Status
        /// </summary>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum PENDING for value: PENDING
            /// </summary>
            PENDING = 1,

            /// <summary>
            /// Enum REQUIRESACTION for value: REQUIRES_ACTION
            /// </summary>
            REQUIRESACTION = 2,

            /// <summary>
            /// Enum PENDINGRECONCILIATION for value: PENDING_RECONCILIATION
            /// </summary>
            PENDINGRECONCILIATION = 3,

            /// <summary>
            /// Enum SUCCESS for value: SUCCESS
            /// </summary>
            SUCCESS = 4,

            /// <summary>
            /// Enum FAILED for value: FAILED
            /// </summary>
            FAILED = 5,

            /// <summary>
            /// Enum CANCELLED for value: CANCELLED
            /// </summary>
            CANCELLED = 6
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("PENDING"))
                return StatusEnum.PENDING;

            if (value.Equals("REQUIRES_ACTION"))
                return StatusEnum.REQUIRESACTION;

            if (value.Equals("PENDING_RECONCILIATION"))
                return StatusEnum.PENDINGRECONCILIATION;

            if (value.Equals("SUCCESS"))
                return StatusEnum.SUCCESS;

            if (value.Equals("FAILED"))
                return StatusEnum.FAILED;

            if (value.Equals("CANCELLED"))
                return StatusEnum.CANCELLED;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("PENDING"))
                return StatusEnum.PENDING;

            if (value.Equals("REQUIRES_ACTION"))
                return StatusEnum.REQUIRESACTION;

            if (value.Equals("PENDING_RECONCILIATION"))
                return StatusEnum.PENDINGRECONCILIATION;

            if (value.Equals("SUCCESS"))
                return StatusEnum.SUCCESS;

            if (value.Equals("FAILED"))
                return StatusEnum.FAILED;

            if (value.Equals("CANCELLED"))
                return StatusEnum.CANCELLED;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum? value)
        {
            if (value == StatusEnum.PENDING)
                return "PENDING";

            if (value == StatusEnum.REQUIRESACTION)
                return "REQUIRES_ACTION";

            if (value == StatusEnum.PENDINGRECONCILIATION)
                return "PENDING_RECONCILIATION";

            if (value == StatusEnum.SUCCESS)
                return "SUCCESS";

            if (value == StatusEnum.FAILED)
                return "FAILED";

            if (value == StatusEnum.CANCELLED)
                return "CANCELLED";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<StatusEnum?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public StatusEnum? Status { get { return this.StatusOption.Value; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Defines ErrorType
        /// </summary>
        public enum ErrorTypeEnum
        {
            /// <summary>
            /// Enum NETWORK for value: NETWORK
            /// </summary>
            NETWORK = 1,

            /// <summary>
            /// Enum TIMEOUT for value: TIMEOUT
            /// </summary>
            TIMEOUT = 2,

            /// <summary>
            /// Enum AUTHENTICATION for value: AUTHENTICATION
            /// </summary>
            AUTHENTICATION = 3,

            /// <summary>
            /// Enum PROVIDERDOWN for value: PROVIDER_DOWN
            /// </summary>
            PROVIDERDOWN = 4,

            /// <summary>
            /// Enum BADREQUEST for value: BAD_REQUEST
            /// </summary>
            BADREQUEST = 5,

            /// <summary>
            /// Enum INTERNALERROR for value: INTERNAL_ERROR
            /// </summary>
            INTERNALERROR = 6,

            /// <summary>
            /// Enum UNKNOWN for value: UNKNOWN
            /// </summary>
            UNKNOWN = 7
        }

        /// <summary>
        /// Returns a <see cref="ErrorTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ErrorTypeEnum ErrorTypeEnumFromString(string value)
        {
            if (value.Equals("NETWORK"))
                return ErrorTypeEnum.NETWORK;

            if (value.Equals("TIMEOUT"))
                return ErrorTypeEnum.TIMEOUT;

            if (value.Equals("AUTHENTICATION"))
                return ErrorTypeEnum.AUTHENTICATION;

            if (value.Equals("PROVIDER_DOWN"))
                return ErrorTypeEnum.PROVIDERDOWN;

            if (value.Equals("BAD_REQUEST"))
                return ErrorTypeEnum.BADREQUEST;

            if (value.Equals("INTERNAL_ERROR"))
                return ErrorTypeEnum.INTERNALERROR;

            if (value.Equals("UNKNOWN"))
                return ErrorTypeEnum.UNKNOWN;

            throw new NotImplementedException($"Could not convert value to type ErrorTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ErrorTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ErrorTypeEnum? ErrorTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("NETWORK"))
                return ErrorTypeEnum.NETWORK;

            if (value.Equals("TIMEOUT"))
                return ErrorTypeEnum.TIMEOUT;

            if (value.Equals("AUTHENTICATION"))
                return ErrorTypeEnum.AUTHENTICATION;

            if (value.Equals("PROVIDER_DOWN"))
                return ErrorTypeEnum.PROVIDERDOWN;

            if (value.Equals("BAD_REQUEST"))
                return ErrorTypeEnum.BADREQUEST;

            if (value.Equals("INTERNAL_ERROR"))
                return ErrorTypeEnum.INTERNALERROR;

            if (value.Equals("UNKNOWN"))
                return ErrorTypeEnum.UNKNOWN;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ErrorTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ErrorTypeEnumToJsonValue(ErrorTypeEnum? value)
        {
            if (value == ErrorTypeEnum.NETWORK)
                return "NETWORK";

            if (value == ErrorTypeEnum.TIMEOUT)
                return "TIMEOUT";

            if (value == ErrorTypeEnum.AUTHENTICATION)
                return "AUTHENTICATION";

            if (value == ErrorTypeEnum.PROVIDERDOWN)
                return "PROVIDER_DOWN";

            if (value == ErrorTypeEnum.BADREQUEST)
                return "BAD_REQUEST";

            if (value == ErrorTypeEnum.INTERNALERROR)
                return "INTERNAL_ERROR";

            if (value == ErrorTypeEnum.UNKNOWN)
                return "UNKNOWN";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of ErrorType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ErrorTypeEnum?> ErrorTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets ErrorType
        /// </summary>
        [JsonPropertyName("errorType")]
        public ErrorTypeEnum? ErrorType { get { return this.ErrorTypeOption.Value; } set { this.ErrorTypeOption = new(value); } }

        /// <summary>
        /// Defines FailureStage
        /// </summary>
        public enum FailureStageEnum
        {
            /// <summary>
            /// Enum VALIDATION for value: VALIDATION
            /// </summary>
            VALIDATION = 1,

            /// <summary>
            /// Enum ROUTING for value: ROUTING
            /// </summary>
            ROUTING = 2,

            /// <summary>
            /// Enum PROVIDERINIT for value: PROVIDER_INIT
            /// </summary>
            PROVIDERINIT = 3,

            /// <summary>
            /// Enum PROVIDERACTION for value: PROVIDER_ACTION
            /// </summary>
            PROVIDERACTION = 4,

            /// <summary>
            /// Enum PROVIDERCALLBACK for value: PROVIDER_CALLBACK
            /// </summary>
            PROVIDERCALLBACK = 5,

            /// <summary>
            /// Enum RECONCILIATION for value: RECONCILIATION
            /// </summary>
            RECONCILIATION = 6,

            /// <summary>
            /// Enum INTERNAL for value: INTERNAL
            /// </summary>
            INTERNAL = 7,

            /// <summary>
            /// Enum UNKNOWN for value: UNKNOWN
            /// </summary>
            UNKNOWN = 8
        }

        /// <summary>
        /// Returns a <see cref="FailureStageEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static FailureStageEnum FailureStageEnumFromString(string value)
        {
            if (value.Equals("VALIDATION"))
                return FailureStageEnum.VALIDATION;

            if (value.Equals("ROUTING"))
                return FailureStageEnum.ROUTING;

            if (value.Equals("PROVIDER_INIT"))
                return FailureStageEnum.PROVIDERINIT;

            if (value.Equals("PROVIDER_ACTION"))
                return FailureStageEnum.PROVIDERACTION;

            if (value.Equals("PROVIDER_CALLBACK"))
                return FailureStageEnum.PROVIDERCALLBACK;

            if (value.Equals("RECONCILIATION"))
                return FailureStageEnum.RECONCILIATION;

            if (value.Equals("INTERNAL"))
                return FailureStageEnum.INTERNAL;

            if (value.Equals("UNKNOWN"))
                return FailureStageEnum.UNKNOWN;

            throw new NotImplementedException($"Could not convert value to type FailureStageEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="FailureStageEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static FailureStageEnum? FailureStageEnumFromStringOrDefault(string value)
        {
            if (value.Equals("VALIDATION"))
                return FailureStageEnum.VALIDATION;

            if (value.Equals("ROUTING"))
                return FailureStageEnum.ROUTING;

            if (value.Equals("PROVIDER_INIT"))
                return FailureStageEnum.PROVIDERINIT;

            if (value.Equals("PROVIDER_ACTION"))
                return FailureStageEnum.PROVIDERACTION;

            if (value.Equals("PROVIDER_CALLBACK"))
                return FailureStageEnum.PROVIDERCALLBACK;

            if (value.Equals("RECONCILIATION"))
                return FailureStageEnum.RECONCILIATION;

            if (value.Equals("INTERNAL"))
                return FailureStageEnum.INTERNAL;

            if (value.Equals("UNKNOWN"))
                return FailureStageEnum.UNKNOWN;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="FailureStageEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string FailureStageEnumToJsonValue(FailureStageEnum? value)
        {
            if (value == FailureStageEnum.VALIDATION)
                return "VALIDATION";

            if (value == FailureStageEnum.ROUTING)
                return "ROUTING";

            if (value == FailureStageEnum.PROVIDERINIT)
                return "PROVIDER_INIT";

            if (value == FailureStageEnum.PROVIDERACTION)
                return "PROVIDER_ACTION";

            if (value == FailureStageEnum.PROVIDERCALLBACK)
                return "PROVIDER_CALLBACK";

            if (value == FailureStageEnum.RECONCILIATION)
                return "RECONCILIATION";

            if (value == FailureStageEnum.INTERNAL)
                return "INTERNAL";

            if (value == FailureStageEnum.UNKNOWN)
                return "UNKNOWN";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of FailureStage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<FailureStageEnum?> FailureStageOption { get; private set; }

        /// <summary>
        /// Gets or Sets FailureStage
        /// </summary>
        [JsonPropertyName("failureStage")]
        public FailureStageEnum? FailureStage { get { return this.FailureStageOption.Value; } set { this.FailureStageOption = new(value); } }

        /// <summary>
        /// Used to track the state of PaymentId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PaymentIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets PaymentId
        /// </summary>
        [JsonPropertyName("paymentId")]
        public string? PaymentId { get { return this.PaymentIdOption.Value; } set { this.PaymentIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of PaymentUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PaymentUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets PaymentUrl
        /// </summary>
        [JsonPropertyName("paymentUrl")]
        public string? PaymentUrl { get { return this.PaymentUrlOption.Value; } set { this.PaymentUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of Provider
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ProviderOption { get; private set; }

        /// <summary>
        /// Gets or Sets Provider
        /// </summary>
        [JsonPropertyName("provider")]
        public string? Provider { get { return this.ProviderOption.Value; } set { this.ProviderOption = new(value); } }

        /// <summary>
        /// Used to track the state of FlowType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FlowTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets FlowType
        /// </summary>
        [JsonPropertyName("flowType")]
        public string? FlowType { get { return this.FlowTypeOption.Value; } set { this.FlowTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Operator
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OperatorOption { get; private set; }

        /// <summary>
        /// Gets or Sets Operator
        /// </summary>
        [JsonPropertyName("operator")]
        public string? Operator { get { return this.OperatorOption.Value; } set { this.OperatorOption = new(value); } }

        /// <summary>
        /// Used to track the state of Country
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CountryOption { get; private set; }

        /// <summary>
        /// Gets or Sets Country
        /// </summary>
        [JsonPropertyName("country")]
        public string? Country { get { return this.CountryOption.Value; } set { this.CountryOption = new(value); } }

        /// <summary>
        /// Used to track the state of Amount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> AmountOption { get; private set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [JsonPropertyName("amount")]
        public decimal? Amount { get { return this.AmountOption.Value; } set { this.AmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of Currency
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CurrencyOption { get; private set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [JsonPropertyName("currency")]
        public string? Currency { get { return this.CurrencyOption.Value; } set { this.CurrencyOption = new(value); } }

        /// <summary>
        /// Used to track the state of NextAction
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<NextAction?> NextActionOption { get; private set; }

        /// <summary>
        /// Gets or Sets NextAction
        /// </summary>
        [JsonPropertyName("nextAction")]
        public NextAction? NextAction { get { return this.NextActionOption.Value; } set { this.NextActionOption = new(value); } }

        /// <summary>
        /// Used to track the state of FailureReason
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FailureReasonOption { get; private set; }

        /// <summary>
        /// Gets or Sets FailureReason
        /// </summary>
        [JsonPropertyName("failureReason")]
        public string? FailureReason { get { return this.FailureReasonOption.Value; } set { this.FailureReasonOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MerchantPaymentResponse {\n");
            sb.Append("  PaymentId: ").Append(PaymentId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  PaymentUrl: ").Append(PaymentUrl).Append("\n");
            sb.Append("  Provider: ").Append(Provider).Append("\n");
            sb.Append("  FlowType: ").Append(FlowType).Append("\n");
            sb.Append("  Operator: ").Append(Operator).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  NextAction: ").Append(NextAction).Append("\n");
            sb.Append("  FailureReason: ").Append(FailureReason).Append("\n");
            sb.Append("  ErrorType: ").Append(ErrorType).Append("\n");
            sb.Append("  FailureStage: ").Append(FailureStage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MerchantPaymentResponse" />
    /// </summary>
    public partial class MerchantPaymentResponseJsonConverter : JsonConverter<MerchantPaymentResponse>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="MerchantPaymentResponseJsonConverter" /> class.
        /// </summary>
        public MerchantPaymentResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="MerchantPaymentResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MerchantPaymentResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> paymentId = default;
            Option<MerchantPaymentResponse.StatusEnum?> status = default;
            Option<string?> paymentUrl = default;
            Option<string?> provider = default;
            Option<string?> flowType = default;
            Option<string?> varOperator = default;
            Option<string?> country = default;
            Option<decimal?> amount = default;
            Option<string?> currency = default;
            Option<NextAction?> nextAction = default;
            Option<string?> failureReason = default;
            Option<MerchantPaymentResponse.ErrorTypeEnum?> errorType = default;
            Option<MerchantPaymentResponse.FailureStageEnum?> failureStage = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "paymentId":
                            paymentId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<MerchantPaymentResponse.StatusEnum?>(MerchantPaymentResponse.StatusEnumFromStringOrDefault(statusRawValue));
                            break;
                        case "paymentUrl":
                            paymentUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "provider":
                            provider = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "flowType":
                            flowType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "operator":
                            varOperator = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "country":
                            country = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "amount":
                            amount = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "currency":
                            currency = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "nextAction":
                            nextAction = new Option<NextAction?>(JsonSerializer.Deserialize<NextAction>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "failureReason":
                            failureReason = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "errorType":
                            string? errorTypeRawValue = utf8JsonReader.GetString();
                            if (errorTypeRawValue != null)
                                errorType = new Option<MerchantPaymentResponse.ErrorTypeEnum?>(MerchantPaymentResponse.ErrorTypeEnumFromStringOrDefault(errorTypeRawValue));
                            break;
                        case "failureStage":
                            string? failureStageRawValue = utf8JsonReader.GetString();
                            if (failureStageRawValue != null)
                                failureStage = new Option<MerchantPaymentResponse.FailureStageEnum?>(MerchantPaymentResponse.FailureStageEnumFromStringOrDefault(failureStageRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (paymentId.IsSet && paymentId.Value == null)
                throw new ArgumentNullException(nameof(paymentId), "Property is not nullable for class MerchantPaymentResponse.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class MerchantPaymentResponse.");

            if (paymentUrl.IsSet && paymentUrl.Value == null)
                throw new ArgumentNullException(nameof(paymentUrl), "Property is not nullable for class MerchantPaymentResponse.");

            if (provider.IsSet && provider.Value == null)
                throw new ArgumentNullException(nameof(provider), "Property is not nullable for class MerchantPaymentResponse.");

            if (flowType.IsSet && flowType.Value == null)
                throw new ArgumentNullException(nameof(flowType), "Property is not nullable for class MerchantPaymentResponse.");

            if (varOperator.IsSet && varOperator.Value == null)
                throw new ArgumentNullException(nameof(varOperator), "Property is not nullable for class MerchantPaymentResponse.");

            if (country.IsSet && country.Value == null)
                throw new ArgumentNullException(nameof(country), "Property is not nullable for class MerchantPaymentResponse.");

            if (amount.IsSet && amount.Value == null)
                throw new ArgumentNullException(nameof(amount), "Property is not nullable for class MerchantPaymentResponse.");

            if (currency.IsSet && currency.Value == null)
                throw new ArgumentNullException(nameof(currency), "Property is not nullable for class MerchantPaymentResponse.");

            if (nextAction.IsSet && nextAction.Value == null)
                throw new ArgumentNullException(nameof(nextAction), "Property is not nullable for class MerchantPaymentResponse.");

            if (failureReason.IsSet && failureReason.Value == null)
                throw new ArgumentNullException(nameof(failureReason), "Property is not nullable for class MerchantPaymentResponse.");

            if (errorType.IsSet && errorType.Value == null)
                throw new ArgumentNullException(nameof(errorType), "Property is not nullable for class MerchantPaymentResponse.");

            if (failureStage.IsSet && failureStage.Value == null)
                throw new ArgumentNullException(nameof(failureStage), "Property is not nullable for class MerchantPaymentResponse.");

            return new MerchantPaymentResponse(paymentId, status, paymentUrl, provider, flowType, varOperator, country, amount, currency, nextAction, failureReason, errorType, failureStage);
        }

        /// <summary>
        /// Serializes a <see cref="MerchantPaymentResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="merchantPaymentResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MerchantPaymentResponse merchantPaymentResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, merchantPaymentResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MerchantPaymentResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="merchantPaymentResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MerchantPaymentResponse merchantPaymentResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (merchantPaymentResponse.PaymentIdOption.IsSet && merchantPaymentResponse.PaymentId == null)
                throw new ArgumentNullException(nameof(merchantPaymentResponse.PaymentId), "Property is required for class MerchantPaymentResponse.");

            if (merchantPaymentResponse.PaymentUrlOption.IsSet && merchantPaymentResponse.PaymentUrl == null)
                throw new ArgumentNullException(nameof(merchantPaymentResponse.PaymentUrl), "Property is required for class MerchantPaymentResponse.");

            if (merchantPaymentResponse.ProviderOption.IsSet && merchantPaymentResponse.Provider == null)
                throw new ArgumentNullException(nameof(merchantPaymentResponse.Provider), "Property is required for class MerchantPaymentResponse.");

            if (merchantPaymentResponse.FlowTypeOption.IsSet && merchantPaymentResponse.FlowType == null)
                throw new ArgumentNullException(nameof(merchantPaymentResponse.FlowType), "Property is required for class MerchantPaymentResponse.");

            if (merchantPaymentResponse.OperatorOption.IsSet && merchantPaymentResponse.Operator == null)
                throw new ArgumentNullException(nameof(merchantPaymentResponse.Operator), "Property is required for class MerchantPaymentResponse.");

            if (merchantPaymentResponse.CountryOption.IsSet && merchantPaymentResponse.Country == null)
                throw new ArgumentNullException(nameof(merchantPaymentResponse.Country), "Property is required for class MerchantPaymentResponse.");

            if (merchantPaymentResponse.CurrencyOption.IsSet && merchantPaymentResponse.Currency == null)
                throw new ArgumentNullException(nameof(merchantPaymentResponse.Currency), "Property is required for class MerchantPaymentResponse.");

            if (merchantPaymentResponse.NextActionOption.IsSet && merchantPaymentResponse.NextAction == null)
                throw new ArgumentNullException(nameof(merchantPaymentResponse.NextAction), "Property is required for class MerchantPaymentResponse.");

            if (merchantPaymentResponse.FailureReasonOption.IsSet && merchantPaymentResponse.FailureReason == null)
                throw new ArgumentNullException(nameof(merchantPaymentResponse.FailureReason), "Property is required for class MerchantPaymentResponse.");

            if (merchantPaymentResponse.PaymentIdOption.IsSet)
                writer.WriteString("paymentId", merchantPaymentResponse.PaymentId);

            var statusRawValue = MerchantPaymentResponse.StatusEnumToJsonValue(merchantPaymentResponse.StatusOption.Value!.Value);
            writer.WriteString("status", statusRawValue);
            if (merchantPaymentResponse.PaymentUrlOption.IsSet)
                writer.WriteString("paymentUrl", merchantPaymentResponse.PaymentUrl);

            if (merchantPaymentResponse.ProviderOption.IsSet)
                writer.WriteString("provider", merchantPaymentResponse.Provider);

            if (merchantPaymentResponse.FlowTypeOption.IsSet)
                writer.WriteString("flowType", merchantPaymentResponse.FlowType);

            if (merchantPaymentResponse.OperatorOption.IsSet)
                writer.WriteString("operator", merchantPaymentResponse.Operator);

            if (merchantPaymentResponse.CountryOption.IsSet)
                writer.WriteString("country", merchantPaymentResponse.Country);

            if (merchantPaymentResponse.AmountOption.IsSet)
                writer.WriteNumber("amount", merchantPaymentResponse.AmountOption.Value!.Value);

            if (merchantPaymentResponse.CurrencyOption.IsSet)
                writer.WriteString("currency", merchantPaymentResponse.Currency);

            if (merchantPaymentResponse.NextActionOption.IsSet)
            {
                writer.WritePropertyName("nextAction");
                JsonSerializer.Serialize(writer, merchantPaymentResponse.NextAction, jsonSerializerOptions);
            }
            if (merchantPaymentResponse.FailureReasonOption.IsSet)
                writer.WriteString("failureReason", merchantPaymentResponse.FailureReason);

            var errorTypeRawValue = MerchantPaymentResponse.ErrorTypeEnumToJsonValue(merchantPaymentResponse.ErrorTypeOption.Value!.Value);
            writer.WriteString("errorType", errorTypeRawValue);
            var failureStageRawValue = MerchantPaymentResponse.FailureStageEnumToJsonValue(merchantPaymentResponse.FailureStageOption.Value!.Value);
            writer.WriteString("failureStage", failureStageRawValue);
        }
    }
}
