// <auto-generated>
/*
 * FidelityPay Merchant SDK API
 *
 * Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using fidelitypay_sdk.Client;

namespace fidelitypay_sdk.Model
{
    /// <summary>
    /// MerchantPaymentRequest
    /// </summary>
    public partial class MerchantPaymentRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MerchantPaymentRequest" /> class.
        /// </summary>
        /// <param name="currency">currency</param>
        /// <param name="country">country</param>
        /// <param name="operator">operator</param>
        /// <param name="customer">customer</param>
        /// <param name="amount">amount</param>
        /// <param name="returnUrl">returnUrl</param>
        /// <param name="cancelUrl">cancelUrl</param>
        [JsonConstructor]
        public MerchantPaymentRequest(string currency, string country, string @operator, Customer customer, Option<long?> amount = default, Option<string?> returnUrl = default, Option<string?> cancelUrl = default)
        {
            Currency = currency;
            Country = country;
            Operator = @operator;
            Customer = customer;
            AmountOption = amount;
            ReturnUrlOption = returnUrl;
            CancelUrlOption = cancelUrl;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [JsonPropertyName("currency")]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or Sets Country
        /// </summary>
        [JsonPropertyName("country")]
        public string Country { get; set; }

        /// <summary>
        /// Gets or Sets Operator
        /// </summary>
        [JsonPropertyName("operator")]
        public string Operator { get; set; }

        /// <summary>
        /// Gets or Sets Customer
        /// </summary>
        [JsonPropertyName("customer")]
        public Customer Customer { get; set; }

        /// <summary>
        /// Used to track the state of Amount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> AmountOption { get; private set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [JsonPropertyName("amount")]
        public long? Amount { get { return this.AmountOption.Value; } set { this.AmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of ReturnUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ReturnUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReturnUrl
        /// </summary>
        [JsonPropertyName("returnUrl")]
        public string? ReturnUrl { get { return this.ReturnUrlOption.Value; } set { this.ReturnUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of CancelUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CancelUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets CancelUrl
        /// </summary>
        [JsonPropertyName("cancelUrl")]
        public string? CancelUrl { get { return this.CancelUrlOption.Value; } set { this.CancelUrlOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MerchantPaymentRequest {\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  Operator: ").Append(Operator).Append("\n");
            sb.Append("  Customer: ").Append(Customer).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  ReturnUrl: ").Append(ReturnUrl).Append("\n");
            sb.Append("  CancelUrl: ").Append(CancelUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (this.Currency != null) {
                // Currency (string) pattern
                Regex regexCurrency = new Regex(@"XOF", RegexOptions.CultureInvariant);

                if (!regexCurrency.Match(this.Currency).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Currency, must match a pattern of " + regexCurrency, new [] { "Currency" });
                }
            }

            // Country (string) maxLength
            if (this.Country != null && this.Country.Length > 3)
            {
                yield return new ValidationResult("Invalid value for Country, length must be less than 3.", new [] { "Country" });
            }

            // Country (string) minLength
            if (this.Country != null && this.Country.Length < 2)
            {
                yield return new ValidationResult("Invalid value for Country, length must be greater than 2.", new [] { "Country" });
            }

            // Operator (string) maxLength
            if (this.Operator != null && this.Operator.Length > 50)
            {
                yield return new ValidationResult("Invalid value for Operator, length must be less than 50.", new [] { "Operator" });
            }

            // Operator (string) minLength
            if (this.Operator != null && this.Operator.Length < 0)
            {
                yield return new ValidationResult("Invalid value for Operator, length must be greater than 0.", new [] { "Operator" });
            }

            // Amount (long) minimum
            if (this.AmountOption.IsSet && this.AmountOption.Value < (long)1)
            {
                yield return new ValidationResult("Invalid value for Amount, must be a value greater than or equal to 1.", new [] { "Amount" });
            }

            // ReturnUrl (string) maxLength
            if (this.ReturnUrl != null && this.ReturnUrl.Length > 1000)
            {
                yield return new ValidationResult("Invalid value for ReturnUrl, length must be less than 1000.", new [] { "ReturnUrl" });
            }

            // ReturnUrl (string) minLength
            if (this.ReturnUrl != null && this.ReturnUrl.Length < 0)
            {
                yield return new ValidationResult("Invalid value for ReturnUrl, length must be greater than 0.", new [] { "ReturnUrl" });
            }

            // CancelUrl (string) maxLength
            if (this.CancelUrl != null && this.CancelUrl.Length > 1000)
            {
                yield return new ValidationResult("Invalid value for CancelUrl, length must be less than 1000.", new [] { "CancelUrl" });
            }

            // CancelUrl (string) minLength
            if (this.CancelUrl != null && this.CancelUrl.Length < 0)
            {
                yield return new ValidationResult("Invalid value for CancelUrl, length must be greater than 0.", new [] { "CancelUrl" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MerchantPaymentRequest" />
    /// </summary>
    public partial class MerchantPaymentRequestJsonConverter : JsonConverter<MerchantPaymentRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="MerchantPaymentRequestJsonConverter" /> class.
        /// </summary>
        public MerchantPaymentRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="MerchantPaymentRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MerchantPaymentRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> currency = default;
            Option<string?> country = default;
            Option<string?> varOperator = default;
            Option<Customer?> customer = default;
            Option<long?> amount = default;
            Option<string?> returnUrl = default;
            Option<string?> cancelUrl = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "currency":
                            currency = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "country":
                            country = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "operator":
                            varOperator = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "customer":
                            customer = new Option<Customer?>(JsonSerializer.Deserialize<Customer>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "amount":
                            amount = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "returnUrl":
                            returnUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "cancelUrl":
                            cancelUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!currency.IsSet)
                throw new ArgumentException("Property is required for class MerchantPaymentRequest.", nameof(currency));

            if (!country.IsSet)
                throw new ArgumentException("Property is required for class MerchantPaymentRequest.", nameof(country));

            if (!varOperator.IsSet)
                throw new ArgumentException("Property is required for class MerchantPaymentRequest.", nameof(varOperator));

            if (!customer.IsSet)
                throw new ArgumentException("Property is required for class MerchantPaymentRequest.", nameof(customer));

            if (currency.IsSet && currency.Value == null)
                throw new ArgumentNullException(nameof(currency), "Property is not nullable for class MerchantPaymentRequest.");

            if (country.IsSet && country.Value == null)
                throw new ArgumentNullException(nameof(country), "Property is not nullable for class MerchantPaymentRequest.");

            if (varOperator.IsSet && varOperator.Value == null)
                throw new ArgumentNullException(nameof(varOperator), "Property is not nullable for class MerchantPaymentRequest.");

            if (customer.IsSet && customer.Value == null)
                throw new ArgumentNullException(nameof(customer), "Property is not nullable for class MerchantPaymentRequest.");

            if (amount.IsSet && amount.Value == null)
                throw new ArgumentNullException(nameof(amount), "Property is not nullable for class MerchantPaymentRequest.");

            if (returnUrl.IsSet && returnUrl.Value == null)
                throw new ArgumentNullException(nameof(returnUrl), "Property is not nullable for class MerchantPaymentRequest.");

            if (cancelUrl.IsSet && cancelUrl.Value == null)
                throw new ArgumentNullException(nameof(cancelUrl), "Property is not nullable for class MerchantPaymentRequest.");

            return new MerchantPaymentRequest(currency.Value!, country.Value!, varOperator.Value!, customer.Value!, amount, returnUrl, cancelUrl);
        }

        /// <summary>
        /// Serializes a <see cref="MerchantPaymentRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="merchantPaymentRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MerchantPaymentRequest merchantPaymentRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, merchantPaymentRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MerchantPaymentRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="merchantPaymentRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MerchantPaymentRequest merchantPaymentRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (merchantPaymentRequest.Currency == null)
                throw new ArgumentNullException(nameof(merchantPaymentRequest.Currency), "Property is required for class MerchantPaymentRequest.");

            if (merchantPaymentRequest.Country == null)
                throw new ArgumentNullException(nameof(merchantPaymentRequest.Country), "Property is required for class MerchantPaymentRequest.");

            if (merchantPaymentRequest.Operator == null)
                throw new ArgumentNullException(nameof(merchantPaymentRequest.Operator), "Property is required for class MerchantPaymentRequest.");

            if (merchantPaymentRequest.Customer == null)
                throw new ArgumentNullException(nameof(merchantPaymentRequest.Customer), "Property is required for class MerchantPaymentRequest.");

            if (merchantPaymentRequest.ReturnUrlOption.IsSet && merchantPaymentRequest.ReturnUrl == null)
                throw new ArgumentNullException(nameof(merchantPaymentRequest.ReturnUrl), "Property is required for class MerchantPaymentRequest.");

            if (merchantPaymentRequest.CancelUrlOption.IsSet && merchantPaymentRequest.CancelUrl == null)
                throw new ArgumentNullException(nameof(merchantPaymentRequest.CancelUrl), "Property is required for class MerchantPaymentRequest.");

            writer.WriteString("currency", merchantPaymentRequest.Currency);

            writer.WriteString("country", merchantPaymentRequest.Country);

            writer.WriteString("operator", merchantPaymentRequest.Operator);

            writer.WritePropertyName("customer");
            JsonSerializer.Serialize(writer, merchantPaymentRequest.Customer, jsonSerializerOptions);
            if (merchantPaymentRequest.AmountOption.IsSet)
                writer.WriteNumber("amount", merchantPaymentRequest.AmountOption.Value!.Value);

            if (merchantPaymentRequest.ReturnUrlOption.IsSet)
                writer.WriteString("returnUrl", merchantPaymentRequest.ReturnUrl);

            if (merchantPaymentRequest.CancelUrlOption.IsSet)
                writer.WriteString("cancelUrl", merchantPaymentRequest.CancelUrl);
        }
    }
}
