// <auto-generated>
/*
 * FidelityPay Merchant SDK API
 *
 * Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using fidelitypay_sdk.Client;

namespace fidelitypay_sdk.Model
{
    /// <summary>
    /// NextAction
    /// </summary>
    public partial class NextAction : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NextAction" /> class.
        /// </summary>
        /// <param name="type">type</param>
        /// <param name="provider">provider</param>
        /// <param name="message">message</param>
        [JsonConstructor]
        public NextAction(Option<string?> type = default, Option<string?> provider = default, Option<string?> message = default)
        {
            TypeOption = type;
            ProviderOption = provider;
            MessageOption = message;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public string? Type { get { return this.TypeOption.Value; } set { this.TypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Provider
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ProviderOption { get; private set; }

        /// <summary>
        /// Gets or Sets Provider
        /// </summary>
        [JsonPropertyName("provider")]
        public string? Provider { get { return this.ProviderOption.Value; } set { this.ProviderOption = new(value); } }

        /// <summary>
        /// Used to track the state of Message
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [JsonPropertyName("message")]
        public string? Message { get { return this.MessageOption.Value; } set { this.MessageOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NextAction {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Provider: ").Append(Provider).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NextAction" />
    /// </summary>
    public partial class NextActionJsonConverter : JsonConverter<NextAction>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="NextActionJsonConverter" /> class.
        /// </summary>
        public NextActionJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="NextAction" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override NextAction Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> type = default;
            Option<string?> provider = default;
            Option<string?> message = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "type":
                            type = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "provider":
                            provider = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class NextAction.");

            if (provider.IsSet && provider.Value == null)
                throw new ArgumentNullException(nameof(provider), "Property is not nullable for class NextAction.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class NextAction.");

            return new NextAction(type, provider, message);
        }

        /// <summary>
        /// Serializes a <see cref="NextAction" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="nextAction"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, NextAction nextAction, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, nextAction, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="NextAction" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="nextAction"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, NextAction nextAction, JsonSerializerOptions jsonSerializerOptions)
        {
            if (nextAction.TypeOption.IsSet && nextAction.Type == null)
                throw new ArgumentNullException(nameof(nextAction.Type), "Property is required for class NextAction.");

            if (nextAction.ProviderOption.IsSet && nextAction.Provider == null)
                throw new ArgumentNullException(nameof(nextAction.Provider), "Property is required for class NextAction.");

            if (nextAction.MessageOption.IsSet && nextAction.Message == null)
                throw new ArgumentNullException(nameof(nextAction.Message), "Property is required for class NextAction.");

            if (nextAction.TypeOption.IsSet)
                writer.WriteString("type", nextAction.Type);

            if (nextAction.ProviderOption.IsSet)
                writer.WriteString("provider", nextAction.Provider);

            if (nextAction.MessageOption.IsSet)
                writer.WriteString("message", nextAction.Message);
        }
    }
}
