// <auto-generated>
/*
 * FidelityPay Merchant SDK API
 *
 * Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using fidelitypay_sdk.Client;

namespace fidelitypay_sdk.Model
{
    /// <summary>
    /// OtpActionRequest
    /// </summary>
    public partial class OtpActionRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OtpActionRequest" /> class.
        /// </summary>
        /// <param name="otp">otp</param>
        [JsonConstructor]
        public OtpActionRequest(string otp)
        {
            Otp = otp;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Otp
        /// </summary>
        [JsonPropertyName("otp")]
        public string Otp { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OtpActionRequest {\n");
            sb.Append("  Otp: ").Append(Otp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Otp (string) maxLength
            if (this.Otp != null && this.Otp.Length > 12)
            {
                yield return new ValidationResult("Invalid value for Otp, length must be less than 12.", new [] { "Otp" });
            }

            // Otp (string) minLength
            if (this.Otp != null && this.Otp.Length < 3)
            {
                yield return new ValidationResult("Invalid value for Otp, length must be greater than 3.", new [] { "Otp" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OtpActionRequest" />
    /// </summary>
    public partial class OtpActionRequestJsonConverter : JsonConverter<OtpActionRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="OtpActionRequestJsonConverter" /> class.
        /// </summary>
        public OtpActionRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="OtpActionRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OtpActionRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> otp = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "otp":
                            otp = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!otp.IsSet)
                throw new ArgumentException("Property is required for class OtpActionRequest.", nameof(otp));

            if (otp.IsSet && otp.Value == null)
                throw new ArgumentNullException(nameof(otp), "Property is not nullable for class OtpActionRequest.");

            return new OtpActionRequest(otp.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="OtpActionRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="otpActionRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OtpActionRequest otpActionRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, otpActionRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OtpActionRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="otpActionRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OtpActionRequest otpActionRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (otpActionRequest.Otp == null)
                throw new ArgumentNullException(nameof(otpActionRequest.Otp), "Property is required for class OtpActionRequest.");

            writer.WriteString("otp", otpActionRequest.Otp);
        }
    }
}
