/*
 * FidelityPay Merchant SDK API
 * Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.MerchantPaymentRequest;
import org.openapitools.client.model.MerchantPaymentResponse;
import org.openapitools.client.model.OtpActionRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class MerchantPayInApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public MerchantPayInApi() {
        this(Configuration.getDefaultApiClient());
    }

    public MerchantPayInApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getPayment
     * @param xAPIKey  (required)
     * @param paymentId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPaymentCall(@javax.annotation.Nonnull String xAPIKey, @javax.annotation.Nonnull String paymentId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/payments/{paymentId}"
            .replace("{" + "paymentId" + "}", localVarApiClient.escapeString(paymentId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xAPIKey != null) {
            localVarHeaderParams.put("X-API-Key", localVarApiClient.parameterToString(xAPIKey));
        }


        String[] localVarAuthNames = new String[] { "apiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPaymentValidateBeforeCall(@javax.annotation.Nonnull String xAPIKey, @javax.annotation.Nonnull String paymentId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'xAPIKey' is set
        if (xAPIKey == null) {
            throw new ApiException("Missing the required parameter 'xAPIKey' when calling getPayment(Async)");
        }

        // verify the required parameter 'paymentId' is set
        if (paymentId == null) {
            throw new ApiException("Missing the required parameter 'paymentId' when calling getPayment(Async)");
        }

        return getPaymentCall(xAPIKey, paymentId, _callback);

    }

    /**
     * Read a merchant pay-in
     * 
     * @param xAPIKey  (required)
     * @param paymentId  (required)
     * @return MerchantPaymentResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public MerchantPaymentResponse getPayment(@javax.annotation.Nonnull String xAPIKey, @javax.annotation.Nonnull String paymentId) throws ApiException {
        ApiResponse<MerchantPaymentResponse> localVarResp = getPaymentWithHttpInfo(xAPIKey, paymentId);
        return localVarResp.getData();
    }

    /**
     * Read a merchant pay-in
     * 
     * @param xAPIKey  (required)
     * @param paymentId  (required)
     * @return ApiResponse&lt;MerchantPaymentResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<MerchantPaymentResponse> getPaymentWithHttpInfo(@javax.annotation.Nonnull String xAPIKey, @javax.annotation.Nonnull String paymentId) throws ApiException {
        okhttp3.Call localVarCall = getPaymentValidateBeforeCall(xAPIKey, paymentId, null);
        Type localVarReturnType = new TypeToken<MerchantPaymentResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Read a merchant pay-in (asynchronously)
     * 
     * @param xAPIKey  (required)
     * @param paymentId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPaymentAsync(@javax.annotation.Nonnull String xAPIKey, @javax.annotation.Nonnull String paymentId, final ApiCallback<MerchantPaymentResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getPaymentValidateBeforeCall(xAPIKey, paymentId, _callback);
        Type localVarReturnType = new TypeToken<MerchantPaymentResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for initiate
     * @param xAPIKey  (required)
     * @param idempotencyKey  (required)
     * @param merchantPaymentRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call initiateCall(@javax.annotation.Nonnull String xAPIKey, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull MerchantPaymentRequest merchantPaymentRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = merchantPaymentRequest;

        // create path and map variables
        String localVarPath = "/api/v1/payments/initiate";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xAPIKey != null) {
            localVarHeaderParams.put("X-API-Key", localVarApiClient.parameterToString(xAPIKey));
        }


        if (idempotencyKey != null) {
            localVarHeaderParams.put("Idempotency-Key", localVarApiClient.parameterToString(idempotencyKey));
        }


        String[] localVarAuthNames = new String[] { "apiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call initiateValidateBeforeCall(@javax.annotation.Nonnull String xAPIKey, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull MerchantPaymentRequest merchantPaymentRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'xAPIKey' is set
        if (xAPIKey == null) {
            throw new ApiException("Missing the required parameter 'xAPIKey' when calling initiate(Async)");
        }

        // verify the required parameter 'idempotencyKey' is set
        if (idempotencyKey == null) {
            throw new ApiException("Missing the required parameter 'idempotencyKey' when calling initiate(Async)");
        }

        // verify the required parameter 'merchantPaymentRequest' is set
        if (merchantPaymentRequest == null) {
            throw new ApiException("Missing the required parameter 'merchantPaymentRequest' when calling initiate(Async)");
        }

        return initiateCall(xAPIKey, idempotencyKey, merchantPaymentRequest, _callback);

    }

    /**
     * Initiate a merchant pay-in
     * Public API endpoint for merchant servers and SDKs. Uses X-API-Key and Idempotency-Key headers.
     * @param xAPIKey  (required)
     * @param idempotencyKey  (required)
     * @param merchantPaymentRequest  (required)
     * @return MerchantPaymentResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public MerchantPaymentResponse initiate(@javax.annotation.Nonnull String xAPIKey, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull MerchantPaymentRequest merchantPaymentRequest) throws ApiException {
        ApiResponse<MerchantPaymentResponse> localVarResp = initiateWithHttpInfo(xAPIKey, idempotencyKey, merchantPaymentRequest);
        return localVarResp.getData();
    }

    /**
     * Initiate a merchant pay-in
     * Public API endpoint for merchant servers and SDKs. Uses X-API-Key and Idempotency-Key headers.
     * @param xAPIKey  (required)
     * @param idempotencyKey  (required)
     * @param merchantPaymentRequest  (required)
     * @return ApiResponse&lt;MerchantPaymentResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<MerchantPaymentResponse> initiateWithHttpInfo(@javax.annotation.Nonnull String xAPIKey, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull MerchantPaymentRequest merchantPaymentRequest) throws ApiException {
        okhttp3.Call localVarCall = initiateValidateBeforeCall(xAPIKey, idempotencyKey, merchantPaymentRequest, null);
        Type localVarReturnType = new TypeToken<MerchantPaymentResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Initiate a merchant pay-in (asynchronously)
     * Public API endpoint for merchant servers and SDKs. Uses X-API-Key and Idempotency-Key headers.
     * @param xAPIKey  (required)
     * @param idempotencyKey  (required)
     * @param merchantPaymentRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call initiateAsync(@javax.annotation.Nonnull String xAPIKey, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull MerchantPaymentRequest merchantPaymentRequest, final ApiCallback<MerchantPaymentResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = initiateValidateBeforeCall(xAPIKey, idempotencyKey, merchantPaymentRequest, _callback);
        Type localVarReturnType = new TypeToken<MerchantPaymentResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for submitOtp
     * @param xAPIKey  (required)
     * @param paymentId  (required)
     * @param otpActionRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call submitOtpCall(@javax.annotation.Nonnull String xAPIKey, @javax.annotation.Nonnull String paymentId, @javax.annotation.Nonnull OtpActionRequest otpActionRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = otpActionRequest;

        // create path and map variables
        String localVarPath = "/api/v1/payments/{paymentId}/actions/otp"
            .replace("{" + "paymentId" + "}", localVarApiClient.escapeString(paymentId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xAPIKey != null) {
            localVarHeaderParams.put("X-API-Key", localVarApiClient.parameterToString(xAPIKey));
        }


        String[] localVarAuthNames = new String[] { "apiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call submitOtpValidateBeforeCall(@javax.annotation.Nonnull String xAPIKey, @javax.annotation.Nonnull String paymentId, @javax.annotation.Nonnull OtpActionRequest otpActionRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'xAPIKey' is set
        if (xAPIKey == null) {
            throw new ApiException("Missing the required parameter 'xAPIKey' when calling submitOtp(Async)");
        }

        // verify the required parameter 'paymentId' is set
        if (paymentId == null) {
            throw new ApiException("Missing the required parameter 'paymentId' when calling submitOtp(Async)");
        }

        // verify the required parameter 'otpActionRequest' is set
        if (otpActionRequest == null) {
            throw new ApiException("Missing the required parameter 'otpActionRequest' when calling submitOtp(Async)");
        }

        return submitOtpCall(xAPIKey, paymentId, otpActionRequest, _callback);

    }

    /**
     * Submit a required OTP action
     * 
     * @param xAPIKey  (required)
     * @param paymentId  (required)
     * @param otpActionRequest  (required)
     * @return MerchantPaymentResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public MerchantPaymentResponse submitOtp(@javax.annotation.Nonnull String xAPIKey, @javax.annotation.Nonnull String paymentId, @javax.annotation.Nonnull OtpActionRequest otpActionRequest) throws ApiException {
        ApiResponse<MerchantPaymentResponse> localVarResp = submitOtpWithHttpInfo(xAPIKey, paymentId, otpActionRequest);
        return localVarResp.getData();
    }

    /**
     * Submit a required OTP action
     * 
     * @param xAPIKey  (required)
     * @param paymentId  (required)
     * @param otpActionRequest  (required)
     * @return ApiResponse&lt;MerchantPaymentResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<MerchantPaymentResponse> submitOtpWithHttpInfo(@javax.annotation.Nonnull String xAPIKey, @javax.annotation.Nonnull String paymentId, @javax.annotation.Nonnull OtpActionRequest otpActionRequest) throws ApiException {
        okhttp3.Call localVarCall = submitOtpValidateBeforeCall(xAPIKey, paymentId, otpActionRequest, null);
        Type localVarReturnType = new TypeToken<MerchantPaymentResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Submit a required OTP action (asynchronously)
     * 
     * @param xAPIKey  (required)
     * @param paymentId  (required)
     * @param otpActionRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call submitOtpAsync(@javax.annotation.Nonnull String xAPIKey, @javax.annotation.Nonnull String paymentId, @javax.annotation.Nonnull OtpActionRequest otpActionRequest, final ApiCallback<MerchantPaymentResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = submitOtpValidateBeforeCall(xAPIKey, paymentId, otpActionRequest, _callback);
        Type localVarReturnType = new TypeToken<MerchantPaymentResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
