/**
 * FidelityPay Merchant SDK API
 * Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NextAction from './NextAction';

/**
 * The MerchantPaymentResponse model module.
 * @module model/MerchantPaymentResponse
 * @version 1.0.0
 */
class MerchantPaymentResponse {
    /**
     * Constructs a new <code>MerchantPaymentResponse</code>.
     * @alias module:model/MerchantPaymentResponse
     */
    constructor() { 
        
        MerchantPaymentResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MerchantPaymentResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerchantPaymentResponse} obj Optional instance to populate.
     * @return {module:model/MerchantPaymentResponse} The populated <code>MerchantPaymentResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerchantPaymentResponse();

            if (data.hasOwnProperty('paymentId')) {
                obj['paymentId'] = ApiClient.convertToType(data['paymentId'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('paymentUrl')) {
                obj['paymentUrl'] = ApiClient.convertToType(data['paymentUrl'], 'String');
            }
            if (data.hasOwnProperty('provider')) {
                obj['provider'] = ApiClient.convertToType(data['provider'], 'String');
            }
            if (data.hasOwnProperty('flowType')) {
                obj['flowType'] = ApiClient.convertToType(data['flowType'], 'String');
            }
            if (data.hasOwnProperty('operator')) {
                obj['operator'] = ApiClient.convertToType(data['operator'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('nextAction')) {
                obj['nextAction'] = NextAction.constructFromObject(data['nextAction']);
            }
            if (data.hasOwnProperty('failureReason')) {
                obj['failureReason'] = ApiClient.convertToType(data['failureReason'], 'String');
            }
            if (data.hasOwnProperty('errorType')) {
                obj['errorType'] = ApiClient.convertToType(data['errorType'], 'String');
            }
            if (data.hasOwnProperty('failureStage')) {
                obj['failureStage'] = ApiClient.convertToType(data['failureStage'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MerchantPaymentResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MerchantPaymentResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['paymentId'] && !(typeof data['paymentId'] === 'string' || data['paymentId'] instanceof String)) {
            throw new Error("Expected the field `paymentId` to be a primitive type in the JSON string but got " + data['paymentId']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['paymentUrl'] && !(typeof data['paymentUrl'] === 'string' || data['paymentUrl'] instanceof String)) {
            throw new Error("Expected the field `paymentUrl` to be a primitive type in the JSON string but got " + data['paymentUrl']);
        }
        // ensure the json data is a string
        if (data['provider'] && !(typeof data['provider'] === 'string' || data['provider'] instanceof String)) {
            throw new Error("Expected the field `provider` to be a primitive type in the JSON string but got " + data['provider']);
        }
        // ensure the json data is a string
        if (data['flowType'] && !(typeof data['flowType'] === 'string' || data['flowType'] instanceof String)) {
            throw new Error("Expected the field `flowType` to be a primitive type in the JSON string but got " + data['flowType']);
        }
        // ensure the json data is a string
        if (data['operator'] && !(typeof data['operator'] === 'string' || data['operator'] instanceof String)) {
            throw new Error("Expected the field `operator` to be a primitive type in the JSON string but got " + data['operator']);
        }
        // ensure the json data is a string
        if (data['country'] && !(typeof data['country'] === 'string' || data['country'] instanceof String)) {
            throw new Error("Expected the field `country` to be a primitive type in the JSON string but got " + data['country']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // validate the optional field `nextAction`
        if (data['nextAction']) { // data not null
          NextAction.validateJSON(data['nextAction']);
        }
        // ensure the json data is a string
        if (data['failureReason'] && !(typeof data['failureReason'] === 'string' || data['failureReason'] instanceof String)) {
            throw new Error("Expected the field `failureReason` to be a primitive type in the JSON string but got " + data['failureReason']);
        }
        // ensure the json data is a string
        if (data['errorType'] && !(typeof data['errorType'] === 'string' || data['errorType'] instanceof String)) {
            throw new Error("Expected the field `errorType` to be a primitive type in the JSON string but got " + data['errorType']);
        }
        // ensure the json data is a string
        if (data['failureStage'] && !(typeof data['failureStage'] === 'string' || data['failureStage'] instanceof String)) {
            throw new Error("Expected the field `failureStage` to be a primitive type in the JSON string but got " + data['failureStage']);
        }

        return true;
    }


}



/**
 * @member {String} paymentId
 */
MerchantPaymentResponse.prototype['paymentId'] = undefined;

/**
 * @member {module:model/MerchantPaymentResponse.StatusEnum} status
 */
MerchantPaymentResponse.prototype['status'] = undefined;

/**
 * @member {String} paymentUrl
 */
MerchantPaymentResponse.prototype['paymentUrl'] = undefined;

/**
 * @member {String} provider
 */
MerchantPaymentResponse.prototype['provider'] = undefined;

/**
 * @member {String} flowType
 */
MerchantPaymentResponse.prototype['flowType'] = undefined;

/**
 * @member {String} operator
 */
MerchantPaymentResponse.prototype['operator'] = undefined;

/**
 * @member {String} country
 */
MerchantPaymentResponse.prototype['country'] = undefined;

/**
 * @member {Number} amount
 */
MerchantPaymentResponse.prototype['amount'] = undefined;

/**
 * @member {String} currency
 */
MerchantPaymentResponse.prototype['currency'] = undefined;

/**
 * @member {module:model/NextAction} nextAction
 */
MerchantPaymentResponse.prototype['nextAction'] = undefined;

/**
 * @member {String} failureReason
 */
MerchantPaymentResponse.prototype['failureReason'] = undefined;

/**
 * @member {module:model/MerchantPaymentResponse.ErrorTypeEnum} errorType
 */
MerchantPaymentResponse.prototype['errorType'] = undefined;

/**
 * @member {module:model/MerchantPaymentResponse.FailureStageEnum} failureStage
 */
MerchantPaymentResponse.prototype['failureStage'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
MerchantPaymentResponse['StatusEnum'] = {

    /**
     * value: "PENDING"
     * @const
     */
    "PENDING": "PENDING",

    /**
     * value: "REQUIRES_ACTION"
     * @const
     */
    "REQUIRES_ACTION": "REQUIRES_ACTION",

    /**
     * value: "PENDING_RECONCILIATION"
     * @const
     */
    "PENDING_RECONCILIATION": "PENDING_RECONCILIATION",

    /**
     * value: "SUCCESS"
     * @const
     */
    "SUCCESS": "SUCCESS",

    /**
     * value: "FAILED"
     * @const
     */
    "FAILED": "FAILED",

    /**
     * value: "CANCELLED"
     * @const
     */
    "CANCELLED": "CANCELLED"
};


/**
 * Allowed values for the <code>errorType</code> property.
 * @enum {String}
 * @readonly
 */
MerchantPaymentResponse['ErrorTypeEnum'] = {

    /**
     * value: "NETWORK"
     * @const
     */
    "NETWORK": "NETWORK",

    /**
     * value: "TIMEOUT"
     * @const
     */
    "TIMEOUT": "TIMEOUT",

    /**
     * value: "AUTHENTICATION"
     * @const
     */
    "AUTHENTICATION": "AUTHENTICATION",

    /**
     * value: "PROVIDER_DOWN"
     * @const
     */
    "PROVIDER_DOWN": "PROVIDER_DOWN",

    /**
     * value: "BAD_REQUEST"
     * @const
     */
    "BAD_REQUEST": "BAD_REQUEST",

    /**
     * value: "INTERNAL_ERROR"
     * @const
     */
    "INTERNAL_ERROR": "INTERNAL_ERROR",

    /**
     * value: "UNKNOWN"
     * @const
     */
    "UNKNOWN": "UNKNOWN"
};


/**
 * Allowed values for the <code>failureStage</code> property.
 * @enum {String}
 * @readonly
 */
MerchantPaymentResponse['FailureStageEnum'] = {

    /**
     * value: "VALIDATION"
     * @const
     */
    "VALIDATION": "VALIDATION",

    /**
     * value: "ROUTING"
     * @const
     */
    "ROUTING": "ROUTING",

    /**
     * value: "PROVIDER_INIT"
     * @const
     */
    "PROVIDER_INIT": "PROVIDER_INIT",

    /**
     * value: "PROVIDER_ACTION"
     * @const
     */
    "PROVIDER_ACTION": "PROVIDER_ACTION",

    /**
     * value: "PROVIDER_CALLBACK"
     * @const
     */
    "PROVIDER_CALLBACK": "PROVIDER_CALLBACK",

    /**
     * value: "RECONCILIATION"
     * @const
     */
    "RECONCILIATION": "RECONCILIATION",

    /**
     * value: "INTERNAL"
     * @const
     */
    "INTERNAL": "INTERNAL",

    /**
     * value: "UNKNOWN"
     * @const
     */
    "UNKNOWN": "UNKNOWN"
};



export default MerchantPaymentResponse;

