/**
 * FidelityPay Merchant SDK API
 * Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Customer from './Customer';

/**
 * The MerchantPaymentRequest model module.
 * @module model/MerchantPaymentRequest
 * @version 1.0.0
 */
class MerchantPaymentRequest {
    /**
     * Constructs a new <code>MerchantPaymentRequest</code>.
     * @alias module:model/MerchantPaymentRequest
     * @param currency {String} 
     * @param country {String} 
     * @param operator {String} 
     * @param customer {module:model/Customer} 
     */
    constructor(currency, country, operator, customer) { 
        
        MerchantPaymentRequest.initialize(this, currency, country, operator, customer);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, currency, country, operator, customer) { 
        obj['currency'] = currency;
        obj['country'] = country;
        obj['operator'] = operator;
        obj['customer'] = customer;
    }

    /**
     * Constructs a <code>MerchantPaymentRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerchantPaymentRequest} obj Optional instance to populate.
     * @return {module:model/MerchantPaymentRequest} The populated <code>MerchantPaymentRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerchantPaymentRequest();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('operator')) {
                obj['operator'] = ApiClient.convertToType(data['operator'], 'String');
            }
            if (data.hasOwnProperty('customer')) {
                obj['customer'] = Customer.constructFromObject(data['customer']);
            }
            if (data.hasOwnProperty('returnUrl')) {
                obj['returnUrl'] = ApiClient.convertToType(data['returnUrl'], 'String');
            }
            if (data.hasOwnProperty('cancelUrl')) {
                obj['cancelUrl'] = ApiClient.convertToType(data['cancelUrl'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MerchantPaymentRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MerchantPaymentRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MerchantPaymentRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // ensure the json data is a string
        if (data['country'] && !(typeof data['country'] === 'string' || data['country'] instanceof String)) {
            throw new Error("Expected the field `country` to be a primitive type in the JSON string but got " + data['country']);
        }
        // ensure the json data is a string
        if (data['operator'] && !(typeof data['operator'] === 'string' || data['operator'] instanceof String)) {
            throw new Error("Expected the field `operator` to be a primitive type in the JSON string but got " + data['operator']);
        }
        // validate the optional field `customer`
        if (data['customer']) { // data not null
          Customer.validateJSON(data['customer']);
        }
        // ensure the json data is a string
        if (data['returnUrl'] && !(typeof data['returnUrl'] === 'string' || data['returnUrl'] instanceof String)) {
            throw new Error("Expected the field `returnUrl` to be a primitive type in the JSON string but got " + data['returnUrl']);
        }
        // ensure the json data is a string
        if (data['cancelUrl'] && !(typeof data['cancelUrl'] === 'string' || data['cancelUrl'] instanceof String)) {
            throw new Error("Expected the field `cancelUrl` to be a primitive type in the JSON string but got " + data['cancelUrl']);
        }

        return true;
    }


}

MerchantPaymentRequest.RequiredProperties = ["currency", "country", "operator", "customer"];

/**
 * @member {Number} amount
 */
MerchantPaymentRequest.prototype['amount'] = undefined;

/**
 * @member {String} currency
 */
MerchantPaymentRequest.prototype['currency'] = undefined;

/**
 * @member {String} country
 */
MerchantPaymentRequest.prototype['country'] = undefined;

/**
 * @member {String} operator
 */
MerchantPaymentRequest.prototype['operator'] = undefined;

/**
 * @member {module:model/Customer} customer
 */
MerchantPaymentRequest.prototype['customer'] = undefined;

/**
 * @member {String} returnUrl
 */
MerchantPaymentRequest.prototype['returnUrl'] = undefined;

/**
 * @member {String} cancelUrl
 */
MerchantPaymentRequest.prototype['cancelUrl'] = undefined;






export default MerchantPaymentRequest;

