/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package fidelitypay_sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import fidelitypay_sdk.models.MerchantPaymentRequest
import fidelitypay_sdk.models.MerchantPaymentResponse
import fidelitypay_sdk.models.OtpActionRequest

import com.squareup.moshi.Json

import fidelitypay_sdk.infrastructure.ApiClient
import fidelitypay_sdk.infrastructure.ApiResponse
import fidelitypay_sdk.infrastructure.ClientException
import fidelitypay_sdk.infrastructure.ClientError
import fidelitypay_sdk.infrastructure.ServerException
import fidelitypay_sdk.infrastructure.ServerError
import fidelitypay_sdk.infrastructure.MultiValueMap
import fidelitypay_sdk.infrastructure.PartConfig
import fidelitypay_sdk.infrastructure.RequestConfig
import fidelitypay_sdk.infrastructure.RequestMethod
import fidelitypay_sdk.infrastructure.ResponseType
import fidelitypay_sdk.infrastructure.Success
import fidelitypay_sdk.infrastructure.toMultiValue

open class MerchantPayInApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://localhost:8060")
        }
    }

    /**
     * GET /api/v1/payments/{paymentId}
     * Read a merchant pay-in
     * 
     * @param xAPIKey 
     * @param paymentId 
     * @return MerchantPaymentResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getPayment(xAPIKey: kotlin.String, paymentId: kotlin.String) : MerchantPaymentResponse {
        val localVarResponse = getPaymentWithHttpInfo(xAPIKey = xAPIKey, paymentId = paymentId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MerchantPaymentResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/payments/{paymentId}
     * Read a merchant pay-in
     * 
     * @param xAPIKey 
     * @param paymentId 
     * @return ApiResponse<MerchantPaymentResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getPaymentWithHttpInfo(xAPIKey: kotlin.String, paymentId: kotlin.String) : ApiResponse<MerchantPaymentResponse?> {
        val localVariableConfig = getPaymentRequestConfig(xAPIKey = xAPIKey, paymentId = paymentId)

        return request<Unit, MerchantPaymentResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getPayment
     *
     * @param xAPIKey 
     * @param paymentId 
     * @return RequestConfig
     */
    fun getPaymentRequestConfig(xAPIKey: kotlin.String, paymentId: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xAPIKey.apply { localVariableHeaders["X-API-Key"] = this.toString() }
        
        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/payments/{paymentId}".replace("{"+"paymentId"+"}", encodeURIComponent(paymentId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/payments/initiate
     * Initiate a merchant pay-in
     * Public API endpoint for merchant servers and SDKs. Uses X-API-Key and Idempotency-Key headers.
     * @param xAPIKey 
     * @param idempotencyKey 
     * @param merchantPaymentRequest 
     * @return MerchantPaymentResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun initiate(xAPIKey: kotlin.String, idempotencyKey: kotlin.String, merchantPaymentRequest: MerchantPaymentRequest) : MerchantPaymentResponse {
        val localVarResponse = initiateWithHttpInfo(xAPIKey = xAPIKey, idempotencyKey = idempotencyKey, merchantPaymentRequest = merchantPaymentRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MerchantPaymentResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/payments/initiate
     * Initiate a merchant pay-in
     * Public API endpoint for merchant servers and SDKs. Uses X-API-Key and Idempotency-Key headers.
     * @param xAPIKey 
     * @param idempotencyKey 
     * @param merchantPaymentRequest 
     * @return ApiResponse<MerchantPaymentResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun initiateWithHttpInfo(xAPIKey: kotlin.String, idempotencyKey: kotlin.String, merchantPaymentRequest: MerchantPaymentRequest) : ApiResponse<MerchantPaymentResponse?> {
        val localVariableConfig = initiateRequestConfig(xAPIKey = xAPIKey, idempotencyKey = idempotencyKey, merchantPaymentRequest = merchantPaymentRequest)

        return request<MerchantPaymentRequest, MerchantPaymentResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation initiate
     *
     * @param xAPIKey 
     * @param idempotencyKey 
     * @param merchantPaymentRequest 
     * @return RequestConfig
     */
    fun initiateRequestConfig(xAPIKey: kotlin.String, idempotencyKey: kotlin.String, merchantPaymentRequest: MerchantPaymentRequest) : RequestConfig<MerchantPaymentRequest> {
        val localVariableBody = merchantPaymentRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xAPIKey.apply { localVariableHeaders["X-API-Key"] = this.toString() }
        idempotencyKey.apply { localVariableHeaders["Idempotency-Key"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/payments/initiate",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/payments/{paymentId}/actions/otp
     * Submit a required OTP action
     * 
     * @param xAPIKey 
     * @param paymentId 
     * @param otpActionRequest 
     * @return MerchantPaymentResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun submitOtp(xAPIKey: kotlin.String, paymentId: kotlin.String, otpActionRequest: OtpActionRequest) : MerchantPaymentResponse {
        val localVarResponse = submitOtpWithHttpInfo(xAPIKey = xAPIKey, paymentId = paymentId, otpActionRequest = otpActionRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MerchantPaymentResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/payments/{paymentId}/actions/otp
     * Submit a required OTP action
     * 
     * @param xAPIKey 
     * @param paymentId 
     * @param otpActionRequest 
     * @return ApiResponse<MerchantPaymentResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun submitOtpWithHttpInfo(xAPIKey: kotlin.String, paymentId: kotlin.String, otpActionRequest: OtpActionRequest) : ApiResponse<MerchantPaymentResponse?> {
        val localVariableConfig = submitOtpRequestConfig(xAPIKey = xAPIKey, paymentId = paymentId, otpActionRequest = otpActionRequest)

        return request<OtpActionRequest, MerchantPaymentResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation submitOtp
     *
     * @param xAPIKey 
     * @param paymentId 
     * @param otpActionRequest 
     * @return RequestConfig
     */
    fun submitOtpRequestConfig(xAPIKey: kotlin.String, paymentId: kotlin.String, otpActionRequest: OtpActionRequest) : RequestConfig<OtpActionRequest> {
        val localVariableBody = otpActionRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xAPIKey.apply { localVariableHeaders["X-API-Key"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/payments/{paymentId}/actions/otp".replace("{"+"paymentId"+"}", encodeURIComponent(paymentId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
