/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package fidelitypay_sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import fidelitypay_sdk.apis.MerchantPayInApi
import fidelitypay_sdk.models.MerchantPaymentRequest
import fidelitypay_sdk.models.MerchantPaymentResponse
import fidelitypay_sdk.models.OtpActionRequest

class MerchantPayInApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MerchantPayInApi
        //val apiInstance = MerchantPayInApi()

        // to test getPayment
        should("test getPayment") {
            // uncomment below to test getPayment
            //val xAPIKey : kotlin.String = xAPIKey_example // kotlin.String | 
            //val paymentId : kotlin.String = paymentId_example // kotlin.String | 
            //val result : MerchantPaymentResponse = apiInstance.getPayment(xAPIKey, paymentId)
            //result shouldBe ("TODO")
        }

        // to test initiate
        should("test initiate") {
            // uncomment below to test initiate
            //val xAPIKey : kotlin.String = xAPIKey_example // kotlin.String | 
            //val idempotencyKey : kotlin.String = idempotencyKey_example // kotlin.String | 
            //val merchantPaymentRequest : MerchantPaymentRequest =  // MerchantPaymentRequest | 
            //val result : MerchantPaymentResponse = apiInstance.initiate(xAPIKey, idempotencyKey, merchantPaymentRequest)
            //result shouldBe ("TODO")
        }

        // to test submitOtp
        should("test submitOtp") {
            // uncomment below to test submitOtp
            //val xAPIKey : kotlin.String = xAPIKey_example // kotlin.String | 
            //val paymentId : kotlin.String = paymentId_example // kotlin.String | 
            //val otpActionRequest : OtpActionRequest =  // OtpActionRequest | 
            //val result : MerchantPaymentResponse = apiInstance.submitOtp(xAPIKey, paymentId, otpActionRequest)
            //result shouldBe ("TODO")
        }

    }
}
