/**
 * FidelityPay Merchant SDK API
 * Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import MerchantPaymentRequest from '../model/MerchantPaymentRequest';
import MerchantPaymentResponse from '../model/MerchantPaymentResponse';
import OtpActionRequest from '../model/OtpActionRequest';

/**
* MerchantPayIn service.
* @module api/MerchantPayInApi
* @version 1.0.0
*/
export default class MerchantPayInApi {

    /**
    * Constructs a new MerchantPayInApi. 
    * @alias module:api/MerchantPayInApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getPayment operation.
     * @callback module:api/MerchantPayInApi~getPaymentCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MerchantPaymentResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Read a merchant pay-in
     * @param {String} xAPIKey 
     * @param {String} paymentId 
     * @param {module:api/MerchantPayInApi~getPaymentCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MerchantPaymentResponse}
     */
    getPayment(xAPIKey, paymentId, callback) {
      let postBody = null;
      // verify the required parameter 'xAPIKey' is set
      if (xAPIKey === undefined || xAPIKey === null) {
        throw new Error("Missing the required parameter 'xAPIKey' when calling getPayment");
      }
      // verify the required parameter 'paymentId' is set
      if (paymentId === undefined || paymentId === null) {
        throw new Error("Missing the required parameter 'paymentId' when calling getPayment");
      }

      let pathParams = {
        'paymentId': paymentId
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Key': xAPIKey
      };
      let formParams = {
      };

      let authNames = ['apiKeyAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = MerchantPaymentResponse;
      return this.apiClient.callApi(
        '/api/v1/payments/{paymentId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the initiate operation.
     * @callback module:api/MerchantPayInApi~initiateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MerchantPaymentResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Initiate a merchant pay-in
     * Public API endpoint for merchant servers and SDKs. Uses X-API-Key and Idempotency-Key headers.
     * @param {String} xAPIKey 
     * @param {String} idempotencyKey 
     * @param {module:model/MerchantPaymentRequest} merchantPaymentRequest 
     * @param {module:api/MerchantPayInApi~initiateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MerchantPaymentResponse}
     */
    initiate(xAPIKey, idempotencyKey, merchantPaymentRequest, callback) {
      let postBody = merchantPaymentRequest;
      // verify the required parameter 'xAPIKey' is set
      if (xAPIKey === undefined || xAPIKey === null) {
        throw new Error("Missing the required parameter 'xAPIKey' when calling initiate");
      }
      // verify the required parameter 'idempotencyKey' is set
      if (idempotencyKey === undefined || idempotencyKey === null) {
        throw new Error("Missing the required parameter 'idempotencyKey' when calling initiate");
      }
      // verify the required parameter 'merchantPaymentRequest' is set
      if (merchantPaymentRequest === undefined || merchantPaymentRequest === null) {
        throw new Error("Missing the required parameter 'merchantPaymentRequest' when calling initiate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Key': xAPIKey,
        'Idempotency-Key': idempotencyKey
      };
      let formParams = {
      };

      let authNames = ['apiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = MerchantPaymentResponse;
      return this.apiClient.callApi(
        '/api/v1/payments/initiate', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the submitOtp operation.
     * @callback module:api/MerchantPayInApi~submitOtpCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MerchantPaymentResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Submit a required OTP action
     * @param {String} xAPIKey 
     * @param {String} paymentId 
     * @param {module:model/OtpActionRequest} otpActionRequest 
     * @param {module:api/MerchantPayInApi~submitOtpCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MerchantPaymentResponse}
     */
    submitOtp(xAPIKey, paymentId, otpActionRequest, callback) {
      let postBody = otpActionRequest;
      // verify the required parameter 'xAPIKey' is set
      if (xAPIKey === undefined || xAPIKey === null) {
        throw new Error("Missing the required parameter 'xAPIKey' when calling submitOtp");
      }
      // verify the required parameter 'paymentId' is set
      if (paymentId === undefined || paymentId === null) {
        throw new Error("Missing the required parameter 'paymentId' when calling submitOtp");
      }
      // verify the required parameter 'otpActionRequest' is set
      if (otpActionRequest === undefined || otpActionRequest === null) {
        throw new Error("Missing the required parameter 'otpActionRequest' when calling submitOtp");
      }

      let pathParams = {
        'paymentId': paymentId
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Key': xAPIKey
      };
      let formParams = {
      };

      let authNames = ['apiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = MerchantPaymentResponse;
      return this.apiClient.callApi(
        '/api/v1/payments/{paymentId}/actions/otp', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
