/*
 * FidelityPay Merchant SDK API
 * Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.MerchantPaymentRequest;
import org.openapitools.client.model.MerchantPaymentResponse;
import org.openapitools.client.model.OtpActionRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MerchantPayInApi
 */
@Disabled
public class MerchantPayInApiTest {

    private final MerchantPayInApi api = new MerchantPayInApi();

    /**
     * Read a merchant pay-in
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPaymentTest() throws ApiException {
        String xAPIKey = null;
        String paymentId = null;
        MerchantPaymentResponse response = api.getPayment(xAPIKey, paymentId);
        // TODO: test validations
    }

    /**
     * Initiate a merchant pay-in
     *
     * Public API endpoint for merchant servers and SDKs. Uses X-API-Key and Idempotency-Key headers.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void initiateTest() throws ApiException {
        String xAPIKey = null;
        String idempotencyKey = null;
        MerchantPaymentRequest merchantPaymentRequest = null;
        MerchantPaymentResponse response = api.initiate(xAPIKey, idempotencyKey, merchantPaymentRequest);
        // TODO: test validations
    }

    /**
     * Submit a required OTP action
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void submitOtpTest() throws ApiException {
        String xAPIKey = null;
        String paymentId = null;
        OtpActionRequest otpActionRequest = null;
        MerchantPaymentResponse response = api.submitOtp(xAPIKey, paymentId, otpActionRequest);
        // TODO: test validations
    }

}
