/*
 * FidelityPay Merchant SDK API
 * Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.client.model.NextAction;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * MerchantPaymentResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-06T13:33:53.454751289Z[Etc/UTC]", comments = "Generator version: 7.24.0-SNAPSHOT")
public class MerchantPaymentResponse {
  public static final String SERIALIZED_NAME_PAYMENT_ID = "paymentId";
  @SerializedName(SERIALIZED_NAME_PAYMENT_ID)
  @javax.annotation.Nullable
  private String paymentId;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    PENDING("PENDING"),
    
    REQUIRES_ACTION("REQUIRES_ACTION"),
    
    PENDING_RECONCILIATION("PENDING_RECONCILIATION"),
    
    SUCCESS("SUCCESS"),
    
    FAILED("FAILED"),
    
    CANCELLED("CANCELLED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private StatusEnum status;

  public static final String SERIALIZED_NAME_PAYMENT_URL = "paymentUrl";
  @SerializedName(SERIALIZED_NAME_PAYMENT_URL)
  @javax.annotation.Nullable
  private String paymentUrl;

  public static final String SERIALIZED_NAME_PROVIDER = "provider";
  @SerializedName(SERIALIZED_NAME_PROVIDER)
  @javax.annotation.Nullable
  private String provider;

  public static final String SERIALIZED_NAME_FLOW_TYPE = "flowType";
  @SerializedName(SERIALIZED_NAME_FLOW_TYPE)
  @javax.annotation.Nullable
  private String flowType;

  public static final String SERIALIZED_NAME_OPERATOR = "operator";
  @SerializedName(SERIALIZED_NAME_OPERATOR)
  @javax.annotation.Nullable
  private String operator;

  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  @javax.annotation.Nullable
  private String country;

  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  @javax.annotation.Nullable
  private BigDecimal amount;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  @javax.annotation.Nullable
  private String currency;

  public static final String SERIALIZED_NAME_NEXT_ACTION = "nextAction";
  @SerializedName(SERIALIZED_NAME_NEXT_ACTION)
  @javax.annotation.Nullable
  private NextAction nextAction;

  public static final String SERIALIZED_NAME_FAILURE_REASON = "failureReason";
  @SerializedName(SERIALIZED_NAME_FAILURE_REASON)
  @javax.annotation.Nullable
  private String failureReason;

  /**
   * Gets or Sets errorType
   */
  @JsonAdapter(ErrorTypeEnum.Adapter.class)
  public enum ErrorTypeEnum {
    NETWORK("NETWORK"),
    
    TIMEOUT("TIMEOUT"),
    
    AUTHENTICATION("AUTHENTICATION"),
    
    PROVIDER_DOWN("PROVIDER_DOWN"),
    
    BAD_REQUEST("BAD_REQUEST"),
    
    INTERNAL_ERROR("INTERNAL_ERROR"),
    
    UNKNOWN("UNKNOWN");

    private String value;

    ErrorTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ErrorTypeEnum fromValue(String value) {
      for (ErrorTypeEnum b : ErrorTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ErrorTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ErrorTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ErrorTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ErrorTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ErrorTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_ERROR_TYPE = "errorType";
  @SerializedName(SERIALIZED_NAME_ERROR_TYPE)
  @javax.annotation.Nullable
  private ErrorTypeEnum errorType;

  /**
   * Gets or Sets failureStage
   */
  @JsonAdapter(FailureStageEnum.Adapter.class)
  public enum FailureStageEnum {
    VALIDATION("VALIDATION"),
    
    ROUTING("ROUTING"),
    
    PROVIDER_INIT("PROVIDER_INIT"),
    
    PROVIDER_ACTION("PROVIDER_ACTION"),
    
    PROVIDER_CALLBACK("PROVIDER_CALLBACK"),
    
    RECONCILIATION("RECONCILIATION"),
    
    INTERNAL("INTERNAL"),
    
    UNKNOWN("UNKNOWN");

    private String value;

    FailureStageEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static FailureStageEnum fromValue(String value) {
      for (FailureStageEnum b : FailureStageEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<FailureStageEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FailureStageEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public FailureStageEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return FailureStageEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      FailureStageEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_FAILURE_STAGE = "failureStage";
  @SerializedName(SERIALIZED_NAME_FAILURE_STAGE)
  @javax.annotation.Nullable
  private FailureStageEnum failureStage;

  public MerchantPaymentResponse() {
  }

  public MerchantPaymentResponse paymentId(@javax.annotation.Nullable String paymentId) {
    this.paymentId = paymentId;
    return this;
  }

  /**
   * Get paymentId
   * @return paymentId
   */
  @javax.annotation.Nullable
  public String getPaymentId() {
    return paymentId;
  }

  public void setPaymentId(@javax.annotation.Nullable String paymentId) {
    this.paymentId = paymentId;
  }


  public MerchantPaymentResponse status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public MerchantPaymentResponse paymentUrl(@javax.annotation.Nullable String paymentUrl) {
    this.paymentUrl = paymentUrl;
    return this;
  }

  /**
   * Get paymentUrl
   * @return paymentUrl
   */
  @javax.annotation.Nullable
  public String getPaymentUrl() {
    return paymentUrl;
  }

  public void setPaymentUrl(@javax.annotation.Nullable String paymentUrl) {
    this.paymentUrl = paymentUrl;
  }


  public MerchantPaymentResponse provider(@javax.annotation.Nullable String provider) {
    this.provider = provider;
    return this;
  }

  /**
   * Get provider
   * @return provider
   */
  @javax.annotation.Nullable
  public String getProvider() {
    return provider;
  }

  public void setProvider(@javax.annotation.Nullable String provider) {
    this.provider = provider;
  }


  public MerchantPaymentResponse flowType(@javax.annotation.Nullable String flowType) {
    this.flowType = flowType;
    return this;
  }

  /**
   * Get flowType
   * @return flowType
   */
  @javax.annotation.Nullable
  public String getFlowType() {
    return flowType;
  }

  public void setFlowType(@javax.annotation.Nullable String flowType) {
    this.flowType = flowType;
  }


  public MerchantPaymentResponse operator(@javax.annotation.Nullable String operator) {
    this.operator = operator;
    return this;
  }

  /**
   * Get operator
   * @return operator
   */
  @javax.annotation.Nullable
  public String getOperator() {
    return operator;
  }

  public void setOperator(@javax.annotation.Nullable String operator) {
    this.operator = operator;
  }


  public MerchantPaymentResponse country(@javax.annotation.Nullable String country) {
    this.country = country;
    return this;
  }

  /**
   * Get country
   * @return country
   */
  @javax.annotation.Nullable
  public String getCountry() {
    return country;
  }

  public void setCountry(@javax.annotation.Nullable String country) {
    this.country = country;
  }


  public MerchantPaymentResponse amount(@javax.annotation.Nullable BigDecimal amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Get amount
   * @return amount
   */
  @javax.annotation.Nullable
  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(@javax.annotation.Nullable BigDecimal amount) {
    this.amount = amount;
  }


  public MerchantPaymentResponse currency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @javax.annotation.Nullable
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
  }


  public MerchantPaymentResponse nextAction(@javax.annotation.Nullable NextAction nextAction) {
    this.nextAction = nextAction;
    return this;
  }

  /**
   * Get nextAction
   * @return nextAction
   */
  @javax.annotation.Nullable
  public NextAction getNextAction() {
    return nextAction;
  }

  public void setNextAction(@javax.annotation.Nullable NextAction nextAction) {
    this.nextAction = nextAction;
  }


  public MerchantPaymentResponse failureReason(@javax.annotation.Nullable String failureReason) {
    this.failureReason = failureReason;
    return this;
  }

  /**
   * Get failureReason
   * @return failureReason
   */
  @javax.annotation.Nullable
  public String getFailureReason() {
    return failureReason;
  }

  public void setFailureReason(@javax.annotation.Nullable String failureReason) {
    this.failureReason = failureReason;
  }


  public MerchantPaymentResponse errorType(@javax.annotation.Nullable ErrorTypeEnum errorType) {
    this.errorType = errorType;
    return this;
  }

  /**
   * Get errorType
   * @return errorType
   */
  @javax.annotation.Nullable
  public ErrorTypeEnum getErrorType() {
    return errorType;
  }

  public void setErrorType(@javax.annotation.Nullable ErrorTypeEnum errorType) {
    this.errorType = errorType;
  }


  public MerchantPaymentResponse failureStage(@javax.annotation.Nullable FailureStageEnum failureStage) {
    this.failureStage = failureStage;
    return this;
  }

  /**
   * Get failureStage
   * @return failureStage
   */
  @javax.annotation.Nullable
  public FailureStageEnum getFailureStage() {
    return failureStage;
  }

  public void setFailureStage(@javax.annotation.Nullable FailureStageEnum failureStage) {
    this.failureStage = failureStage;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantPaymentResponse merchantPaymentResponse = (MerchantPaymentResponse) o;
    return Objects.equals(this.paymentId, merchantPaymentResponse.paymentId) &&
        Objects.equals(this.status, merchantPaymentResponse.status) &&
        Objects.equals(this.paymentUrl, merchantPaymentResponse.paymentUrl) &&
        Objects.equals(this.provider, merchantPaymentResponse.provider) &&
        Objects.equals(this.flowType, merchantPaymentResponse.flowType) &&
        Objects.equals(this.operator, merchantPaymentResponse.operator) &&
        Objects.equals(this.country, merchantPaymentResponse.country) &&
        Objects.equals(this.amount, merchantPaymentResponse.amount) &&
        Objects.equals(this.currency, merchantPaymentResponse.currency) &&
        Objects.equals(this.nextAction, merchantPaymentResponse.nextAction) &&
        Objects.equals(this.failureReason, merchantPaymentResponse.failureReason) &&
        Objects.equals(this.errorType, merchantPaymentResponse.errorType) &&
        Objects.equals(this.failureStage, merchantPaymentResponse.failureStage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentId, status, paymentUrl, provider, flowType, operator, country, amount, currency, nextAction, failureReason, errorType, failureStage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantPaymentResponse {\n");
    sb.append("    paymentId: ").append(toIndentedString(paymentId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    paymentUrl: ").append(toIndentedString(paymentUrl)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    flowType: ").append(toIndentedString(flowType)).append("\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    nextAction: ").append(toIndentedString(nextAction)).append("\n");
    sb.append("    failureReason: ").append(toIndentedString(failureReason)).append("\n");
    sb.append("    errorType: ").append(toIndentedString(errorType)).append("\n");
    sb.append("    failureStage: ").append(toIndentedString(failureStage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("paymentId", "status", "paymentUrl", "provider", "flowType", "operator", "country", "amount", "currency", "nextAction", "failureReason", "errorType", "failureStage"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MerchantPaymentResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MerchantPaymentResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in MerchantPaymentResponse is not found in the empty JSON string", MerchantPaymentResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MerchantPaymentResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `MerchantPaymentResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("paymentId") != null && !jsonObj.get("paymentId").isJsonNull()) && !jsonObj.get("paymentId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `paymentId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paymentId").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        StatusEnum.validateJsonElement(jsonObj.get("status"));
      }
      if ((jsonObj.get("paymentUrl") != null && !jsonObj.get("paymentUrl").isJsonNull()) && !jsonObj.get("paymentUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `paymentUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paymentUrl").toString()));
      }
      if ((jsonObj.get("provider") != null && !jsonObj.get("provider").isJsonNull()) && !jsonObj.get("provider").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `provider` to be a primitive type in the JSON string but got `%s`", jsonObj.get("provider").toString()));
      }
      if ((jsonObj.get("flowType") != null && !jsonObj.get("flowType").isJsonNull()) && !jsonObj.get("flowType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `flowType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("flowType").toString()));
      }
      if ((jsonObj.get("operator") != null && !jsonObj.get("operator").isJsonNull()) && !jsonObj.get("operator").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `operator` to be a primitive type in the JSON string but got `%s`", jsonObj.get("operator").toString()));
      }
      if ((jsonObj.get("country") != null && !jsonObj.get("country").isJsonNull()) && !jsonObj.get("country").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `country` to be a primitive type in the JSON string but got `%s`", jsonObj.get("country").toString()));
      }
      if ((jsonObj.get("currency") != null && !jsonObj.get("currency").isJsonNull()) && !jsonObj.get("currency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency").toString()));
      }
      // validate the optional field `nextAction`
      if (jsonObj.get("nextAction") != null && !jsonObj.get("nextAction").isJsonNull()) {
        NextAction.validateJsonElement(jsonObj.get("nextAction"));
      }
      if ((jsonObj.get("failureReason") != null && !jsonObj.get("failureReason").isJsonNull()) && !jsonObj.get("failureReason").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `failureReason` to be a primitive type in the JSON string but got `%s`", jsonObj.get("failureReason").toString()));
      }
      if ((jsonObj.get("errorType") != null && !jsonObj.get("errorType").isJsonNull()) && !jsonObj.get("errorType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `errorType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("errorType").toString()));
      }
      // validate the optional field `errorType`
      if (jsonObj.get("errorType") != null && !jsonObj.get("errorType").isJsonNull()) {
        ErrorTypeEnum.validateJsonElement(jsonObj.get("errorType"));
      }
      if ((jsonObj.get("failureStage") != null && !jsonObj.get("failureStage").isJsonNull()) && !jsonObj.get("failureStage").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `failureStage` to be a primitive type in the JSON string but got `%s`", jsonObj.get("failureStage").toString()));
      }
      // validate the optional field `failureStage`
      if (jsonObj.get("failureStage") != null && !jsonObj.get("failureStage").isJsonNull()) {
        FailureStageEnum.validateJsonElement(jsonObj.get("failureStage"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MerchantPaymentResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MerchantPaymentResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MerchantPaymentResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MerchantPaymentResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<MerchantPaymentResponse>() {
           @Override
           public void write(JsonWriter out, MerchantPaymentResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MerchantPaymentResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MerchantPaymentResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MerchantPaymentResponse
   * @throws IOException if the JSON string is invalid with respect to MerchantPaymentResponse
   */
  public static MerchantPaymentResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MerchantPaymentResponse.class);
  }

  /**
   * Convert an instance of MerchantPaymentResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

