// <auto-generated>
/*
 * FidelityPay Merchant SDK API
 *
 * Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System.Text.Json;

namespace fidelitypay_sdk.Client
{
    /// <summary>
    /// Provides the JsonSerializerOptions
    /// </summary>
    public class JsonSerializerOptionsProvider
    {
        /// <summary>
        /// the JsonSerializerOptions
        /// </summary>
        public JsonSerializerOptions Options { get; }

        /// <summary>
        /// Instantiates a JsonSerializerOptionsProvider
        /// </summary>
        public JsonSerializerOptionsProvider(JsonSerializerOptions options)
        {
            Options = options;
        }
    }
}
