# coding: utf-8

# flake8: noqa
"""
    FidelityPay Merchant SDK API

    Public endpoints for third-party merchant integrations. Authenticate every request with the `X-API-Key` header. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from fidelitypay_sdk.models.customer import Customer
from fidelitypay_sdk.models.merchant_payment_request import MerchantPaymentRequest
from fidelitypay_sdk.models.merchant_payment_response import MerchantPaymentResponse
from fidelitypay_sdk.models.next_action import NextAction
from fidelitypay_sdk.models.otp_action_request import OtpActionRequest

